### ISSUE TITLE
Add volume driver for ceph

### ISSUE THREAD

**Issue by jupiturliu** [libopenstorage/openstorage#102]
Ceph should be support

**Comment by jvinod** [comment]
This is a popular request. There are other ceph drivers that are out there that can be 'ported' to openstorage - would you like to take that on @jupiturliu ?

**Comment by jupiturliu** [comment]
Sure, I will take on this task.

**Comment by jupiturliu** [comment]
I am going to use go ceph bindings, https://github.com/ceph/go-ceph 

Any comments?

Regards,
James

**Comment by jvinod** [comment]
Sounds like a good starting point. How do you plan to take care of the  RADOS dependencies?

**Comment by jupiturliu** [comment]
It is a very good question. So far it requires the developer to install rados library and header files manually. Let me think about it. any suggestions? @jvinod

**Comment by jupiturliu** [comment]
Status update: Ceph cluster is setup in my machine and going to do the test soon with new created ceph volume driver. I will be on&off in coming two weeks due to holiday seasons.

**Comment by gourao** [comment]
Can you try the CoprHD driver.  That should support CEPH.

**Comment by WolfyLPDC** [comment]
I'm sorry for reviving this old post, but, does the CoprHD driver support CEPH? Has it been tested or was it just a guess?

I've seen the request to delete old drivers (inclusing CoprHD) #209 and I would like to know if it was because of the failure or the end of the support.
