### ISSUE TITLE
Include more information about local storage in docs.

### ISSUE THREAD

**Issue by F21** [libopenstorage/openstorage#104]
There doesn't appear to be much information about local storage.

Does it only support btrfs at the moment? Are there any plans to support other filesystems like ext4 or zfs?

Finally, it would be nice to have more documentation of how it works in practice. Does it move data volumes across hosts when containers are rescheduled like flocker's zfs local storage?

**Comment by jvinod** [comment]
Every driver has it's own local storage requirement.  The btrfs driver requires btrfs.  There is an NFS driver which requires an NFS server and so on.

The docs in each driver need to specify this.  I'll open separate bugs for each driver that does not clearly state it's requirements.

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
