### ISSUE TITLE
Error settings up EBS volume

### ISSUE THREAD

**Issue by yoanisgil** [libopenstorage/openstorage#109]
Hi there,

I'm trying to configure OSD to use an EBS volume however when I launch the osd daemon I get this error:

```
osd -d -f /usr/local/etc/osd-config.yml
INFO[0000] Starting volume driver: aws
WARN[0000] Unable to start volume driver: aws, Error querying AWS metadata for key placement/availability-zone: Code 404 returned for url http://169.254.169.254/latest/meta-data/placement/availability-zone
```

the `config.yml` file looks like this:

```
sd:
  drivers:
      aws:
        aws_access_key_id: AWS_KEY_ID
        aws_secret_access_key: AWS_SECRET_KEY
```

any ideas?

**Comment by jvinod** [comment]
Could you try to wget that URL directly from your ec2 instance? That might
give some clues..

**Comment by yoanisgil** [comment]
@jvinod sorry for the very late response. I believe that URL is coming straight from the code. See here:

https://github.com/libopenstorage/openstorage/blob/master/volume/drivers/aws/aws.go#L166

**Comment by jvinod** [comment]
Yes, I understand  - I was wondering if you could directly run

curl -L http://169.254.169.254/latest/meta-data/placement/availability-zone
from
your ec2 instance and post the results - that's aws special url
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by jvinod** [comment]
Ping @yoanisgil - any news?

**Comment by yoanisgil** [comment]
@jvinod sorry for the delay. This is the output:

curl -L http://169.254.169.254/latest/meta-data/placement/availability-zone
us-west-2b

so it looks this URL is only available from AWS internal network. Right?

**Comment by jvinod** [comment]
Oh yes. EBS volume driver is for AWS internal network :)

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
