### ISSUE TITLE
github.com/portworx/systemutils missing

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#110]
```
$ agg systemutils
cluster/manager.go:20:	"github.com/portworx/systemutils"
cluster/manager.go:107:	s := systemutils.New()
api/cluster.go:7:	"github.com/portworx/systemutils"
api/cluster.go:32:	Luns       map[string]systemutils.Lun
```

**Comment by peter-edge** [comment]
ping, somewhat urgent

**Comment by gourao** [comment]
Fixed

**Comment by peter-edge** [comment]
This is not a fix, the vendor directly regularly gets wiped clean and is for external repositories. Systemutils either needs to be restored to the portworx organization, or the code needs to be moved into openstorage.

**Comment by peter-edge** [comment]
Ping again @gourao @jvinod 

One of the following three things needs to be completed ASAP:

1. github.com/portworx/systemutils is restored
2. The relevant code in github.com/portworx/systemutils is moved to a new repo
3. The relevant code in github.com/portworx/systemutils is moved to pkg/

**Comment by jvinod** [comment]
It is moved to libopenstorage...
