### ISSUE TITLE
pkg/stats not used

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#112]
Is this for the future? I would like pkg/ to not depend on api/

**Comment by gourao** [comment]
pkg should not depend on api.

**Comment by peter-edge** [comment]
Can we remove the file pkg/stats/disk.go?

**Comment by jvinod** [comment]
removed - see https://github.com/libopenstorage/openstorage/commit/61f356bc30ed12fa2af9cf4f487a365fd54f6d74
