### ISSUE TITLE
Getting undefined: sockets.ConfigureTCPTransport

### ISSUE THREAD

**Issue by nderzhak** [libopenstorage/openstorage#118]
Enviroment: Ubuntu 15.10 golang 1.5.1 

# GO15VENDOREXPERIMENT=1 go get github.com/libopenstorage/openstorage/...
# github.com/libopenstorage/openstorage/vendor/github.com/docker/docker/pkg/plugins
/root/work/src/github.com/libopenstorage/openstorage/vendor/github.com/docker/docker/pkg/plugins/client.go:34: undefined: sockets.ConfigureTCPTransport

**Comment by nderzhak** [comment]
That is warning I believe.

**Comment by venkatpx** [comment]
This should be addressed with the latest. Pls reopen if you still see this.
