### ISSUE TITLE
During volume create, SDK should not return existing volume not in up state

### ISSUE THREAD

**Issue by harsh-px** [libopenstorage/openstorage#1180]
**BUG REPORT**:

SDK returned an existing volume which will still in down state.

**What happened**:

- 2 volume creates came in at the same time for the same volume name
- While the first create call will still creating the volume, the 2nd create returned the volume as it existed in the inspect response. The volume was still in down state. This caused the k8s PVC to bind to a down volume. The test then created a snapshot in down state since the parent volume was in down state.

https://github.com/libopenstorage/openstorage/blob/master/api/server/sdk/volume_ops.go#L45

**What you expected to happen**:

Return volume only if it is in up state.

**How to reproduce it (as minimally and precisely as possible)**:

1. Trigger 1st create volume call and it should put volume in down state before the 2nd call starts. Don't return from here
2. Trigger 2nd create call for the same name. In current code, it will return a down state volume.

**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version: k8s on openshift (can be reproduced outside of k8s using above)
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lpabon** [comment]
Are these some of the scenarios?

Scenario 1:

1. Delete volume with name A. SDK returns ok, but the driver is still deleting.
1. Create a volume with the name A, SDK returns ok volume id since the old volume is still around and deleting.

Scenario 2:

1. Create a volume with name A
1. SDK returns with volume id for name A, but the volume is still not ready since it is being prepared by the driver.

**Comment by harsh-px** [comment]
> Scenario 1:

Yes, we have seen this scenario too in a different torpedo test.

 > Scenario 2:

Slightly changing this scenario to match the original issue more precisely.

1. time=0sec: Create a volume with name A
2. time=1sec: Another create request for volume with same name A
3. time=2sec: SDK returns with volume id for name A for the 2nd request but but the volume is still not ready since it is being prepared by the driver as part of the first request.
4. time=3sec Caller for second request sees the volume create request succeeded and starts using the volume which still wasn't prepared
5. time=4sec: First volume create request is now complete
