### ISSUE TITLE
WARN[0000] Unable to start volume driver: aws, too many letters "/dev/sda1" 

### ISSUE THREAD

**Issue by nderzhak** [libopenstorage/openstorage#119]
Looks like AWS driver does not support device names with numbers (?).

devPrefix seems to be hardcoded here: https://github.com/libopenstorage/openstorage/blob/master/volume/drivers/aws/aws.go#L115-L129

root@es-100-pem-300-data-1:/home/ubuntu# osd -d -f config.yaml 
INFO[0000] Starting volume driver: aws  
INFO[0000] AWS instance i-3523abf2 zone us-west-2b  
WARN[0000] Unable to start volume driver: aws, too many letters "/dev/sda1" 

root@es-100-pem-300-data-1:/home/ubuntu# ls -l /dev/sd*
ls: cannot access /dev/sd*: No such file or directory

root@es-100-pem-300-data-1:/home/ubuntu# ls -l /dev/xvd**
brw-rw---- 1 root disk 202,  0 Feb 17 22:05 /dev/xvda
brw-rw---- 1 root disk 202,  1 Feb 17 22:05 /dev/xvda1
brw-rw---- 1 root disk 202, 16 Feb 17 22:05 /dev/xvdb

**Comment by drewrobb** [comment]
+1, I also experienced this issue.

**Comment by gourao** [comment]
Pinging @rodriguise

Rob could you take a look at this?

**Comment by rodriguise** [comment]
Looking into it.

**Comment by yoanisgil** [comment]
Also experiencing this issue.

**Comment by rodriguise** [comment]
This is related to kernel inconsistencies

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html

From Amazon: 
Depending on the block device driver of the kernel, the device might be attached with a different name than what you specify. For example, if you specify a device name of /dev/sdh, your device might be renamed /dev/xvdh or /dev/hdh by the kernel; in most cases, the trailing letter remains the same. In some versions of Red Hat Enterprise Linux (and its variants, such as CentOS), even the trailing letter might also change (where /dev/sda could become /dev/xvde). In these cases, each device name trailing letter is incremented the same number of times. For example, /dev/sdb would become /dev/xvdf and /dev/sdc would become /dev/xvdg. Amazon Linux AMIs create a symbolic link with the name you specify at launch that points to the renamed device path, but other AMIs might behave differently.

Currently investigating a workaround.

**Comment by rodriguise** [comment]
PR https://github.com/libopenstorage/openstorage/pull/138 submitted.
