### ISSUE TITLE
Support AWS IAM role credentials

### ISSUE THREAD

**Issue by drewrobb** [libopenstorage/openstorage#120]
Configuration for AWS should not require AWS_ACCESS_KEY_ID vars, if IAM roles are used, the ChainProvided can be used to authenticate with env vars or the IAM role method: https://github.com/libopenstorage/openstorage/blob/b49fab4850a072b05a0bc904ef8c1ad65f27c713/vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go#L86

**Comment by adityadani** [comment]
We now support this.

**Comment by rlewkowicz** [comment]
@adityadani which commit hash do you support this in?

**Comment by adityadani** [comment]
@rlewkowicz What is your exact use case here?
We recently moved the layer that integrated with AWS SDK as well as support for other cloud providers to a separate repository [cloudops](- https://github.com/libopenstorage/cloudops)
