### ISSUE TITLE
Default cos invalid for AWS

### ISSUE THREAD

**Issue by drewrobb** [libopenstorage/openstorage#121]
Running
    osd aws create -s 5000 --cos 1 name

I get:
    create: InvalidParameterCombination: The parameter iops is not supported for gp2 volumes.

It would be nice to be able to specify the volume type and iops directly so that valid combinations could be made

**Comment by gourao** [comment]
+1 

I think the aws driver currently has no way of using provisioned iops volumes... this is something that should be added.

**Comment by rodriguise** [comment]
I am not able to reproduce this issue in master, can you please provide a full usage and use case you are trying achieve.
