### ISSUE TITLE
Zookeeper KVDB support

### ISSUE THREAD

**Issue by drewrobb** [libopenstorage/openstorage#122]
A Zookeeper kvdb implementation would be nice. https://github.com/docker/libkv seems to be very similar to https://github.com/portworx/kvdb and already has zookeeper support.

**Comment by gourao** [comment]
Agreed... bandwidth... if someone wants to provide an implementation, that would be great!

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
