### ISSUE TITLE
how to use layer0 driver？

### ISSUE THREAD

**Issue by manusu** [libopenstorage/openstorage#125]
hi,i'm a new user of openstorage. now i meet a problem.i need some help,thanks.  
I start osd with nfs volume driver successfully.  
then i see https://github.com/libopenstorage/openstorage/blob/master/graph/drivers/layer0/README.md  
if i understand correctly ,i think it tells me to set /etc/default/docker  
    DOCKER_STORAGE_OPTIONS= -s layer0 --storage-opt layer0.volume_driver=aws  
i replace `aws` with `nfs`,and restart my docker service ,but can't connect my docker daemon.  
I don' kown what 's my wrong.how can i use layer0 driver correctly?
thanks for help.

**Comment by gourao** [comment]
What version of Docker are you using?

Can you also provide more details on the error (logs etc)

**Comment by manusu** [comment]
@gourao   
my docker  Version:      1.9.1
my osd config file 
![image](https://cloud.githubusercontent.com/assets/15800670/13803870/31d5c55a-eb83-11e5-863f-63259ed7a1bb.png)
i append DOCKER_STORAGE_OPTIONS= -s layer0 --storage-opt layer0.volume_driver=aws
![image](https://cloud.githubusercontent.com/assets/15800670/13807149/a801de28-eb9a-11e5-94f7-52243bd44c68.png)
i need to do anything else to use layer0 driver?

**Comment by manusu** [comment]
@gourao    layer0 driver is used to persist the topest layer in volume layer,do i understand right?

**Comment by venkatpx** [comment]
We no longer support this.
