### ISSUE TITLE
Suggestion: API/Struct changes

### ISSUE THREAD

**Issue by kunalkushwaha** [libopenstorage/openstorage#13]
Hi,

If any changes in struct or API are done, It should be communicated.

I think a simple process may be followed such changes. 
- A issues can be created for such changes, explaining need of change or just a reference point. 
- After checkin, Update the issue with what changes result into other codebase.

This is with reference of adding checkin https://github.com/libopenstorage/openstorage/commit/e74adf7040d5bff24554b0c34a7ba29248c88ce0

Thanks,
Kunal

**Comment by jvinod** [comment]
sgtm.  That change wasn't a change in struct or API per se but we'll open issues in the future. .Thanks!
