### ISSUE TITLE
Failed to locate volume

### ISSUE THREAD

**Issue by KennethNagin** [libopenstorage/openstorage#135]
I am new to openstorage.  I openstorage and  configured the configure.yaml to
use my nfs server.  However when I run docker volume create -d nfs --name myvolume it does not
create the volume.  osd write out this error message:
WARN[0158] 404   Failed to locate volume: Cannot locate volume myvolume  Driver=nfs ID=myvolume Request=get

Also docker volume ls does not show that the volume was created.

More details:
This is the output when I launch osd:

~/work/src/github.com/libopenstorage/openstorage$ sudo ~/work/bin/osd -d -f etc/config/config.yaml
INFO[0000] OSD enabling cluster mode.                   
INFO[0000] Starting REST service on /var/lib/osd/cluster/osd.sock 
INFO[0000] Starting volume driver: nfs                  
INFO[0000] NFS driver initializing with 9.148.24.228:/var/nfs  
INFO[0000] NFS initialized and driver mounted at:  /var/lib/openstorage/nfs/ 
INFO[0000] Starting REST service on /var/lib/osd/driver/nfs.sock 
INFO[0000] Starting REST service on /run/docker/plugins/nfs.sock 
INFO[0000] Starting graph driver: chainfs               
INFO[0000] Starting REST service on /run/docker/plugins/chainfs.sock 
INFO[0000] Cluster manager starting...                  
INFO[0000] Cluster is uninitialized...                  
INFO[0000] Will initialize a new cluster.               
INFO[0000] Node 1 joining cluster...                    
INFO[0000] Cluster ID: deadbeeef                        
INFO[0000] Node Mgmt IP: 9.148.24.229                   
INFO[0000] Node Data IP: 9.148.24.229                   
INFO[0000] Cluster database updated.  

In the docker log:
agin@rcc-hrl-kvg-587:~$ sudo docker daemon -H unix:///var/run/docker.sock
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
INFO[0000] Firewalld running: false                     
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
WARN[0000] Your kernel does not support swap memory limit. 
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=20f81dd execdriver=native-0.2 graphdriver=aufs version=1.10.3
INFO[0000] API listen on /var/run/docker.sock           
WARN[0021] Unable to connect to plugin: /run/docker/plugins/nfs.sock, retrying in 1s 
WARN[0022] Unable to connect to plugin: /run/docker/plugins/nfs.sock, retrying in 2s 
WARN[0024] Unable to connect to plugin: /run/docker/plugins/nfs.sock, retrying in 4s 
WARN[0028] Unable to connect to plugin: /run/docker/plugins/nfs.sock, retrying in 8s 
ERRO[0036] Handler for POST /v1.22/volumes/create returned error: create myvolume: create myvolume: Error looking up volume plugin nfs: Post http://%2Frun%2Fdocker%2Fplugins%2Fnfs.sock/Plugin.Activate: dial unix /run/docker/plugins/nfs.sock: connect: connection refused 

Also note:
/var/lib/openstorage/nfs/  is indeed mounted to the nfs server.
I can manually add files outside of docker and it works as expected.
Oddly though the mount does not appear in the df -h list.

--Ken

.

**Comment by KennethNagin** [comment]
I got things working.  I'm not sure why the docker volume ls was not showing the created volume, but now it is.

**Comment by peter-edge** [comment]
@KennethNagin can we close this?

**Comment by KennethNagin** [comment]
yes
