### ISSUE TITLE
Move vendored etcd to latest commit

### ISSUE THREAD

**Issue by rodriguise** [libopenstorage/openstorage#144]
The current vendored kvdb/etcd causes a panic, the etcd revision should probably be moved to the latest.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4e6066]

goroutine 43 [running]:
panic(0xee6160, 0xc820010150)
        /root/.gvm/gos/go1.6/src/runtime/panic.go:464 +0x3e6
github.com/libopenstorage/openstorage/vendor/github.com/portworx/kvdb/etcd.(*EtcdKV).refreshLock(0xc8201f4ac0, 0xc8200de660)
        /root/.gvm/pkgsets/go1.6/global/src/github.com/libopenstorage/openstorage/vendor/github.com/portworx/kvdb/etcd/kv_etcd.go:375 +0x3f6
created by github.com/libopenstorage/openstorage/vendor/github.com/portworx/kvdb/etcd.(*EtcdKV).Lock
        /root/.gvm/pkgsets/go1.6/global/src/github.com/libopenstorage/openstorage/vendor/github.com/portworx/kvdb/etcd/kv_etcd.go:351 +0x505

**Comment by jvinod** [comment]
updated, lemme know if you run into this again..

**Comment by peter-edge** [comment]
The commit was reverted, so check this again when the issue is fixed

**Comment by jvinod** [comment]
Fixed https://github.com/libopenstorage/openstorage/commit/8dfa9f923c9db79e9b108f2d7d234228f56f2fe8
