### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#145]
https://github.com/libopenstorage/openstorage/commit/2dfee8715b851bd6027562b6b34a6073c58a9a4c

Please fix ASAP

**Comment by peter-edge** [comment]
Reverted in https://github.com/libopenstorage/openstorage/commit/3a1315854e8345a2f2d92ade26bdf7135b6c813f

**Comment by jvinod** [comment]
fixed
