### ISSUE TITLE
How the kvdb.Kvdb implementation is decided is dangerous

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#146]
https://github.com/libopenstorage/openstorage/blob/f0d5f39a83aa44d4e904f5f10ed770fde5055001/cmd/osd/main.go#L145

From what I can tell, you're relying on the url being something like `consul-kv://, etcd-kv://, kv-mem://`, which is not documented I think, and overall not great. https://github.com/portworx/kvdb/issues/1

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
