### ISSUE TITLE
Instance and global state for kvdb.Kvdb intermixed in alert package

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#148]
You have things like `GetKvdbInstance` which implies there is an instance associated with each `AlertClient`, but with how you use the `kvdb` package, there is only one global instance

**Comment by adityadani** [comment]
Each kvdb instance is associated with a "prefix" generally a clusterID. Now the alert module needs to implement operations like watch or enumerate on different clusters simultaneously. Hence alert module maintains multiple kvdb instances in a map based of clusterID. And depending on the api call's clusterID we select the appropriate kvdb. So, I won't say its inter-mixed but yes we are maintaining multiple kvdb instances.

**Comment by peter-edge** [comment]
https://github.com/portworx/kvdb/blob/master/kvdb_mgr.go

You are using `kvdb.Instance()` eventually, right? Then you are not using multiple instances

**Comment by adityadani** [comment]
No I am not using kvdb.Instance(). To use that singleton instance you need to first call SetInstance(). But I am not calling it. Instead the kvdb object that kvdb.New() returns is maintained in a map. And I maintain multiple such instances.
