### ISSUE TITLE
Documentation to use OSD with AWS

### ISSUE THREAD

**Issue by rca** [libopenstorage/openstorage#149]
While I was able to get the daemon running following the README, I was not able to get it reliably working with AWS EBS volumes.

The first problem I ran into was AWS credentials.  I wrote the config file below to `/etc/osd/config.yaml`:

```
osd:
  drivers:
      aws:
        aws_access_key_id: <my key>
        aws_secret_access_key: <my secret>
```

and when running the daemon I got the error below:

```
root@ip-172-30-0-39:~# ~/osd -d -f /etc/osd/config.yaml
INFO[0000] Starting volume driver: aws
INFO[0000] AWS instance i-a3951724 zone us-east-1a
WARN[0000] Unable to start volume driver: aws, AWS_ACCESS_KEY_ID environment variable must be set
```

I removed the credentials from the file and simply provided them on the command line using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, which successfully launched the daemon.

I have a number of existing volumes in my account and assumed I could just start using them, but instead run into the error:

```
root@ip-172-30-0-39:~# ~admin/osd aws attach vol-45a950eeINFO[0682]                                               Driver=aws ID=vol-45a950ee Request=volumeSet
attach: Volume vol-45a950ee could not be located
```

From that, I assumed OSD wanted to own the entire lifecycle of the volume, so I created one with the `osd aws create` command.  I was then able to `attach`, `mount`, `unmount`, and `detach` the volume OSD created.  But, then I ran into another problem.

Upon stopping the daemon and restarting it, OSD forgot about the volume, so again I got the `attach: Volume vol-45a950ee could not be located` error.

Is there a document that describes how to properly use OSD?

Thank you.

**Comment by jvinod** [comment]
Unless a key-value database is used in conjunction with osd,  the configuration stays in an in-memory key value store.

If you do run osd with -h it will spit out help and one of the params it takes in is a etcd url (you would need to setup etcd, consul support is coming..)
```
-k etcd-kv://localhost:4001
```
If you run it with an etcd backend then the volumes are persistent and will survive restarts.

I'll leave this open till we publish some docs

**Comment by rlewkowicz** [comment]
@jvinod @gourao whats the word on this?
