### ISSUE TITLE
question: Is nomad being considered ?

### ISSUE THREAD

**Issue by joeblew99** [libopenstorage/openstorage#152]
Nomad by Hashicorp is a scheduler, and i was wondering if its being considered to be supported.

As i understand it is does support Docker. I did a quick check to see if it supports the Docker Remote API.

I used Nmad on a previous project and even at version 0.3 (approx , cant rememebr exactly), it was very able and i hit not issues. The usage of it is very easy, and its 100% golang based and so very easy in term of getting going and ops, provisioning etc.

If people could comment i appreciate it.
I want to use openstorage for the current project i am on with nomad if possible.
Also i am really curious what others think about this idea and Nomad.
Its probably well known, but with nomad you can run n Amazon and then move off onto your own bare metal when your ready. This is of course the whole point of openstorgae too.

**Comment by gourao** [comment]
Since OSD runs in a container, yes it can be deployed and managed by Nomad.
