### ISSUE TITLE
Download and use without go

### ISSUE THREAD

**Issue by rupamroy** [libopenstorage/openstorage#155]
Is there a pre-compiled package that i can just download and use instead of installing go and then using it to compile the project ?

**Comment by jvinod** [comment]
You should be able to:
docker pull openstorage/osd

**Comment by rupamroy** [comment]
Looks like to run as a docker container we will need to use the --privileged flag. That will not be allowed in production. Is there some other solution ?

**Comment by KennethNagin** [comment]
I do not understand why docker pull openstorage/osd is a solution, since this a plugin for the docker host.  Doesn't it need to run outside of docker?
I think what is need is distro installations.  For instance, apt-get install  openstorage for Ubuntu.

**Comment by gourao** [comment]
@KennethNagin, OSD runs in a container so it can be distro agnostic.  Therefore the privileged flag is needed... this would be the case even if you did run OSD at the host (it would need to run as a privileged user).
