### ISSUE TITLE
docker operation not permitted

### ISSUE THREAD

**Issue by tszhao** [libopenstorage/openstorage#157]
I'm using the openstorage/osd docker image to start the nfs, command as follow:
`docker run -v /root/osd/config.yaml:/etc/config/config.yaml openstorage/osd -d -f /etc/config/config.yaml
`
but it's go wrong!
time="2016-08-25T10:02:18Z" level=info msg="Starting volume driver: nfs" 
time="2016-08-25T10:02:18Z" level=info msg="NFS driver initializing with 172.16.2.162:/nfs " 
time="2016-08-25T10:02:18Z" level=info msg="Unable to mount 172.16.2.162:/nfs at /var/lib/openstorage/nfs/ (operation not permitted)" 
time="2016-08-25T10:02:18Z" level=warning msg="Unable to start volume driver: nfs, operation not permitted" 

the nfs server's exports:
/nfs *(rw,sync,no_root_squash)

I don't know how to solve it.

**Comment by gourao** [comment]
Can you try and manually mount that path at /var/lib/openstorage/nfs as the same user you are running OSD as?
