### ISSUE TITLE
docker volume rm volume_name fails with key on not found

### ISSUE THREAD

**Issue by KennethNagin** [libopenstorage/openstorage#158]
I'm trying to use osd to provide docker nfs support.  However docker volume rm is not working.
docker volume create is working and the volume is being mounted to nfs.
docker volume ls and docker volume inspect do recognize that the volume has been created.
However, docker volume rm returns an error  Key not found 

This a trace of docker client:
$ sudo docker volume create -d nfs --name myvolume
myvolume
nagin@rcc-hrl-kvg-588:~$ sudo docker volume ls
DRIVER              VOLUME NAME
nfs                 myvolume
$ sudo docker volume inspect myvolume
[
    {
        "Name": "myvolume",
        "Driver": "nfs",
        "Mountpoint": "",
        "Labels": {},
        "Scope": "global"
    }
]

$ sudo docker volume rm myvolume
Error response from daemon: Error while removing volume myvolume: remove myvolume: Key not found

This a trace of osd:
$ sudo ~/work/bin/osd -d -f etc/config/config.yaml
[sudo] password for nagin: 
2016/09/04 13:49:35 proto: duplicate proto type registered: google.protobuf.Empty
INFO[0000] OSD enabling cluster mode.                   
INFO[0000] Starting REST service on socket : /var/lib/osd/cluster/osd.sock 
INFO[0000] Starting volume driver: nfs                  
INFO[0000] NFS driver initializing with 9.148.24.228:/docker_volumes  
INFO[0000] NFS initialized and driver mounted at:  /var/lib/openstorage/nfs/ 
INFO[0000] Starting REST service on socket : /var/lib/osd/driver/nfs.sock 
INFO[0000] Starting REST service on socket : /run/docker/plugins/nfs.sock 
INFO[0000] Starting graph driver: chainfs               
INFO[0000] Starting REST service on socket : /run/docker/plugins/chainfs.sock 
INFO[0000] Cluster manager starting...                  
INFO[0000] Cluster is uninitialized...                  
INFO[0000] Will initialize a new cluster.               
INFO[0000] Node 1 joining cluster...                    
INFO[0000] Cluster ID: deadbeeef                        
INFO[0000] Node Mgmt IP: 9.148.24.230                   
INFO[0000] Node Data IP: 9.148.24.230                   
INFO[0000] Cluster is uninitialized...                  
INFO[0000] Cluster is uninitialized...                  
INFO[0000] Cluster database updated.                    
INFO[0000] Waiting for the cluster to reach quorum...   
INFO[0000] Starting Gossip...                           
2016/09/04 13:49:35 [WARN] memberlist: Binding to public address without encryption!
WARN[0170] 404   Failed to locate volume: Cannot locate volume myvolume  Driver=nfs ID=myvolume Request=get
INFO[0170]                                               Driver=nfs ID=myvolume Request=create
INFO[0170] response global                               Driver=nfs ID= Request=capabilities
INFO[0306] Key not found                                

--Ken

**Comment by gourao** [comment]
Located the problem... looks like a recent regression.  The commands expect the actual volume ID (UUID) and not the friendly name.

If you try the command with the id (shown via osd nfs enumerate), then it will work.

We will have this fixed soon.

**Comment by KennethNagin** [comment]
Please notify me when the fix is available.

**Comment by gourao** [comment]
@KennethNagin Please try the latest code... the fix has been merged

**Comment by KennethNagin** [comment]
It works. Thanks.
--Ken
