### ISSUE TITLE
docker swarm and nfs

### ISSUE THREAD

**Issue by alokag27** [libopenstorage/openstorage#159]
Isetted up docker in swarm mode docker 1.12.1.

I was working on creating the service using nfs driver. 

When i start the service with --mount option i see different volume on different host e.g. host1 will have volume 1 with ID X and host 2 with ID Y. I cant see the same content on different hosts.

docker service create --name web2 --mount type=volume,source=vol1,target=/mnt,volume-driver=nfs httpd

**Comment by gourao** [comment]
This is now resolved
