### ISSUE TITLE
hostname in config.yaml

### ISSUE THREAD

**Issue by alokag27** [libopenstorage/openstorage#160]
if you specify hostname instead of IP address in config.yaml file, osd service does not start. Driver "NFS"

osd:
  drivers:
      nfs:
        server: "hostnameX"
        path: "/nfs"

**Comment by gourao** [comment]
This is an issue with how syscall.Mount works.  You need to specify the IP.

**Comment by gourao** [comment]
Will open an enhancement to do a DNS lookup prior to calling syscall.Mount.  Closing this issue
