### ISSUE TITLE
openstorage/osd not retaining state on restart

### ISSUE THREAD

**Issue by KennethNagin** [libopenstorage/openstorage#161]
I'm using the docker image openstorage/osd  on my docker host to get nfs support.
It creates nfs volumes as expected.
However, if I have to restart the engine or restart the osd container it loses it state.
I have to recreate the volumes. Thankfully the volume data is not lost, but the fact that
that the osd does not remember which volumes it created I think should be remedied.

This docker command that I am using start osd:

sudo docker run -d --restart always --privileged -v /tmp:/tmp -v /var/lib/openstorage/:/var/lib/openstorage/ -v /var/lib/osd/:/var/lib/osd/   -v /run/docker/plugins:/run/docker/plugins --name osd openstorage/osd -d -f /tmp/config_nfs.yaml

--Ken

**Comment by gourao** [comment]
@KennethNagin You need to configure a persistent key value DB such as etcd.

When you start osd, pass in your KVDB URL as a global option via --kvdb

etcd and consul are supported.

Without this, OSD keeps volume mapping in memory and that is not persisted.

To setup etcd, please visit https://coreos.com/etcd/docs/latest/docker_guide.html

I've documented this at https://github.com/libopenstorage/openstorage/blob/master/README.md#starting-osd

**Comment by KennethNagin** [comment]
It seems to be expecting an openstorage key or directory in the key-value storage.  
I've created both but it is still complaining.

nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ sudo docker run --rm -it   --privileged -v /tmp:/tmp -v /var/lib/openstorage/:/var/lib/openstorage/ -v /var/lib/osd/:/var/lib/osd/   -v /run/docker/plugins:/run/docker/plugins  -v /var/lib/docker:/var/lib/docker --name osd openstorage/osd -d -f /tmp/config_nfs.yaml --kvdb etcd-kv://9.148.24.228:4001 
2016/09/20 09:02:46 proto: duplicate proto type registered: google.protobuf.Empty
INFO[0000] OSD enabling cluster mode.                   
INFO[0000] Starting REST service on socket : /var/lib/osd/cluster/osd.sock 
INFO[0000] Starting volume driver: nfs                  
INFO[0000] NFS driver initializing with 9.148.24.228:/docker_volumes  
WARN[0000] Unable to start volume driver: nfs, 100: Key not found (/openstorage) [9] 
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 mk openstorage ""

nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 ls/openstorage
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ sudo docker run --rm -it   --privileged -v /tmp:/tmp -v /var/lib/openstorage/:/var/lib/openstorage/ -v /var/lib/osd/:/var/lib/osd/   -v /run/docker/plugins:/run/docker/plugins  -v /var/lib/docker:/var/lib/docker --name osd openstorage/osd -d -f /tmp/config_nfs.yaml --kvdb etcd-kv://9.148.24.228:4001 
2016/09/20 09:03:37 proto: duplicate proto type registered: google.protobuf.Empty
INFO[0000] OSD enabling cluster mode.                   
INFO[0000] Starting REST service on socket : /var/lib/osd/cluster/osd.sock 
INFO[0000] Starting volume driver: nfs                  
INFO[0000] NFS driver initializing with 9.148.24.228:/docker_volumes  
WARN[0000] Unable to start volume driver: nfs, 104: Not a directory (/openstorage) [10] 
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 rm openstorage

nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 mkdir openstorage
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 ls/openstorage
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ sudo docker run --rm -it   --privileged -v /tmp:/tmp -v /var/lib/openstorage/:/var/lib/openstorage/ -v /var/lib/osd/:/var/lib/osd/   -v /run/docker/plugins:/run/docker/plugins  -v /var/lib/docker:/var/lib/docker --name osd openstorage/osd -d -f /tmp/config_nfs.yaml --kvdb etcd-kv://9.148.24.228:4001 
2016/09/20 09:04:26 proto: duplicate proto type registered: google.protobuf.Empty
INFO[0000] OSD enabling cluster mode.                   
INFO[0000] Starting REST service on socket : /var/lib/osd/cluster/osd.sock 
INFO[0000] Starting volume driver: nfs                  
INFO[0000] NFS driver initializing with 9.148.24.228:/docker_volumes  
WARN[0000] Unable to start volume driver: nfs, 100: Key not found (/openstorage/openstorage) [12] 
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 mk openstorage/openstorage^Cnagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 mk openstorage/openstorage ""

nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 ls/openstorage
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 ls openstorage
/openstorage/openstorage
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ sudo docker run --rm -it   --privileged -v /tmp:/tmp -v /var/lib/openstorage/:/var/lib/openstorage/ -v /var/lib/osd/:/var/lib/osd/   -v /run/docker/plugins:/run/docker/plugins  -v /var/lib/docker:/var/lib/docker --name osd openstorage/osd -d -f /tmp/config_nfs.yaml --kvdb etcd-kv://9.148.24.228:4001 
2016/09/20 09:05:51 proto: duplicate proto type registered: google.protobuf.Empty
INFO[0000] OSD enabling cluster mode.                   
INFO[0000] Starting REST service on socket : /var/lib/osd/cluster/osd.sock 
INFO[0000] Starting volume driver: nfs                  
INFO[0000] NFS driver initializing with 9.148.24.228:/docker_volumes  
WARN[0000] Unable to start volume driver: nfs, 104: Not a directory (/openstorage/openstorage) [13] 
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ etcdctl -C http://9.148.24.228:4001 mk openstorage ""Error:  105: Key already exists (/openstorage) [13]
nagin@rcc-hrl-kvg-588:~/work/src/github.com/libopenstorage/openstorage$ 

--Ken

**Comment by gourao** [comment]
@KennethNagin You should not need anything pre-existing in etcd.  Pinging @jvinod

**Comment by gourao** [comment]
@KennethNagin I have pushed a fix for this.  Please give it a try

**Comment by gourao** [comment]
@KennethNagin Were you able to try the latest code?  I'd like to close this if this is working for you

**Comment by KennethNagin** [comment]
It works.  I think you have a small glitch.  The first time you try to create a volume it spits out a message that it can not find the nfs key.  But other than that it retains its state.
--Ken

**Comment by KennethNagin** [comment]
It looks good. Thanks.  I found a glitch which I explain in my comment.  I 
also opened another ticket which I think you will find  interesting (
https://github.com/libopenstorage/openstorage/issues/163)

Best Regards,

Kenneth Nagin
Ph: +972-4-8296227
Cell: 054-6976227
Fx: +972-4- 8296114
http://researcher.ibm.com/view.php?person=il-NAGIN
