### ISSUE TITLE
docker volume rm not cleaning up completely

### ISSUE THREAD

**Issue by KennethNagin** [libopenstorage/openstorage#163]
docker volume rm is not cleaning up completely.  It is leaving the subject volume in /var/lib/osd/mounts.
The result is that if you remove a volume and then create the volume again its old data persists.

$ sudo docker volume rm myvol
myvol
$ sudo ls /var/lib/openstorage/nfs
$ sudo ls /var/lib/osd/mounts
myvol
$ sudo ls /var/lib/osd/mounts/myvol
file.txt
$ sudo ls /var/lib/openstorage/nfs
$ sudo docker volume create -d nfs --name myvol
myvol
$ sudo docker run --rm -v myvol:/data busybox sh -c "cat /data/file.txt"
 hello

Could you please explain why you need two directories to store the volume, /var/lib/openstorage/nfs and /var/lib/osd/mounts?
One of the undesirable affects of this design is that you have to nfs mount both directories if you want share the volumes across a cluster of docker hosts.

--Ken

**Comment by gourao** [comment]
The reason for the two directories is that /var/lib/openstorage/nfs is where your NFS target gets NFS mounted.

The /var/lib/osd/mounts is what gets "bind" mounted into the container.  You can have multiple clients share the same NFS mount without having to refcount the clients.

That said, what you bring up is certainly a bug... will look at why docker volume rm is not deleting the volume altogether.

**Comment by KennethNagin** [comment]
Assuming that you fix the bug and osd also cleans up the /var/lib/osd/mounts,
it is not clear to me how containers on different docker hosts in a cluster can share the their volumes without nfs mounting both /var/lib/openstorage/nfs and /var/lib/osd/mounts.

--Ken

**Comment by gourao** [comment]
@KennethNagin I am not able to repro your issue with the latest code.  Just to clarify...

1. `docker volume create -d nfs --name myvol` - This will create a share on your NFS server called myvol.  
2. `docker run -it --rm -v myvol:/data busybox /bin/sh` - At this point, the directory `myvol` on your NFS server get's mounted at /var/lib/osd/mounts/myvol which is then bind mounted into the container's namespace.
3. If you were to run another instance of busybox on another server in your cluster, it will see the same contents of the myvol volume.  The two containers are sharing data.
4. If you exit one of the busyboxes and do a `docker volume rm myvol`, then OSD will properly delete the volume from your NFS server and delete all it's contents.  There is no myvol volume anymore.  subsequent `docker volume ls` will not list the volume.  You may see a directory left around in /var/lib/osd/mounts/myvol, but this is benign.  A new volume created with the same name will simply occupy this directory, but you will not see any old contents.

Can you clarify if you are seeing something different from above?

**Comment by KennethNagin** [comment]
As you can see in the sequence below, after volume myvol is removed and then recreated with the same name its content, i.e. file.txt,  persist.  This is one problem.  The other problem is that the contents of  /var/lib/osd/mounts/myvol  will accumulate over time, and eventual use up all the disk space.  
$ sudo docker volume create -d nfs --name myvol
myvol
$ sudo docker run --rm -v myvol:/data busybox sh -c "cat /data/file.txt"
cat: can't open '/data/file.txt': No such file or directory
$ sudo docker run --rm -v myvol:/data busybox sh -c "echo helloworld > /data/file.txt"
$ sudo docker run --rm -v myvol:/data busybox sh -c "cat /data/file.txt"
helloworld
$ sudo docker volume rm myvol
myvol
$ sudo docker volume ls
DRIVER              VOLUME NAME
**$ sudo docker volume create -d nfs --name myvol
myvol
$ sudo docker run --rm -v myvol:/data busybox sh -c "cat /data/file.txt"
helloworld**

**Comment by KennethNagin** [comment]
I think I have discovered the source of the inconsistency between what you are seeing and what I am seeing.  I think you were work directly from the source tree and I was working with the docker image that is published on docker hub.  When I worked with directly with the source I git hub volume rm does not leave the old files around and I get the expected results when re-creating the volume.  Though osd still leaves directories in /var/lib/osd/nfs.  I think this is messing but not a big problem.

However,  I do think there is an inherent problem with using a docker image for distributing the osd plugin. On the docker plugin page (https://docs.docker.com/engine/extend/plugin_api/) it says "Plugins should be started before Docker, and stopped after Docker.".  Of course,  this is impossible if you launch the osd docker image as a container.  I've experience odd results if I did not start osd prior to starting the docker engine.

**Comment by gourao** [comment]
That makes sense now... I will publish a container that has the latest
source

While the docs say plugins should be started first, that is outdated.  As
of docker 1.10, docker has solved this and will start dependent containers
after the plugin containers are started.

Portworx' storage also ships as a container.   If you experience a specific
problem, let me know how to repro

Thanks
Gou

**Comment by venkatpx** [comment]
Pls reopen if the problem happens again. This is resolved in upstream OSD
