### ISSUE TITLE
Unbale to configure/disable Flexvolume support

### ISSUE THREAD

**Issue by multani** [libopenstorage/openstorage#165]
Flexvolume is always activated and always bind to port 2345. The only way to change either of these is to update the source code, recompile and redeploy Openstorage binary

In case Openstorage is not deployed in a Kubernetes environment, this Flexvolume support is useless and opens another port on the machine which could be avoided if it was configurable at runtime.

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.

**Comment by WolfyLPDC** [comment]
I want to report the same problem. When you start the Open Storage Daemon you can set the REST Gateway port and the gRPC port, but flexvolume port is hardcoded to 2345. There should be an option to change this value without recompiling each time a change is needed.

**Comment by adityadani** [comment]
@WolfyLPDC Flexvolume will be deprecated soon and there is no active work going on for it. Openstorage has added the support for CSI (the k8s recommend volume plugin interface)

More information about CSI [here](https://kubernetes.io/docs/concepts/storage/volumes/#csi)

Once CSI is GA, flexvolume will be completely removed from openstorage.

**Comment by WolfyLPDC** [comment]
@adityadani I was saying it just because I wanted to prevent a potential collision with the port 2345, not because of the functionality. However, if it is going to be removed, the result is the same for me.

Thanks for the answer.
