### ISSUE TITLE
AWS driver never releases device ID, raises "No free device IDs" after a while

### ISSUE THREAD

**Issue by multani** [libopenstorage/openstorage#167]
The [AWS driver calls](https://github.com/libopenstorage/openstorage/blob/master/volume/drivers/aws/aws.go#L520) the [`Assign()` function](https://github.com/libopenstorage/openstorage/blob/master/pkg/device/device.go#L48) which removes usable device names from the list of available names but never calls the [matching `Release()` function](https://github.com/libopenstorage/openstorage/blob/master/pkg/device/device.go#L60) although the device is correctly freed.  After a while, Openstorage doesn't have any available usable device names anymore, fails to allocate a device name upon request and returns the "No free device IDs" error message.

Restarting the Openstorage process fixes the problem...

**Comment by ChenPeng2013** [comment]
+1, I also experienced this issue.

**Comment by gourao** [comment]
@zoxpx Can you look at this issue?

**Comment by zoxpx** [comment]
Fix committed at [pull/172](https://github.com/libopenstorage/openstorage/pull/172)

**Manual tests**:
* Before fix, no more than 11 volumes could be created:
```
for i in $(seq 12); do
    sudo $GOPATH/bin/osd -k etcd-kv://localhost:4001 aws create testvol$i -s 1536 --fs ext4 --cos "low"
done

vol-014403e506444b25c
vol-07a417799a7da9692
vol-03b316a8da07bb271
vol-018225cb393001071
vol-0eef767be58bf1467
vol-048413096c3c05720
vol-017cb10659803f593
vol-0a9436c92e4c46b96
vol-0aa63966d11cfe0d5
vol-098c1f312b335b30d
vol-00c01f7163fa37847
create: No free device IDs
```
* After the fix, this test passes successfully (we got our 12 volumes w/o errors).

**Automated tests**:
```
[ec2-user@ip-172-31-45-217 openstorage]$ go test github.com/libopenstorage/openstorage/volume/drivers/aws
ok  	github.com/libopenstorage/openstorage/volume/drivers/aws	0.003s
```

**Comment by zoxpx** [comment]
fix merged into master -- closing issue as resolved.
