### ISSUE TITLE
Why not just apt-get install btrfs-tools in the Dockerfile?

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#17]
I might be missing something. That version (3.12 for Ubuntu 14.04) works just fine for docker's btrfs package (which this go code is using). It would save a lot of pain in the Dockerfile.

**Comment by jvinod** [comment]
I apt-get  works for btrfs-progs (I thought it didn't)  then that's what we should do . Absolutely agree with getting the btrfs build out of Dockerfile if we can

**Comment by peter-edge** [comment]
I'll do this in another PR tomorrow. We do this in https://github.com/pachyderm/pachyderm/blob/master/Dockerfile#L7 for similar reasons. We right now decided against using docker's btrfs package and shell out for various reasons, but I believe that before this still worked properly (when we did use the docker btrfs package).
