### ISSUE TITLE
Fatal, Unable to find self node entry in local cache

### ISSUE THREAD

**Issue by jcmolinos** [libopenstorage/openstorage#170]
After read documentation of:
https://github.com/libopenstorage/openstorage

I tried to install it and I don't have any problem for do it, but when I want to start as a service  with this :

[root@manager1-docker ~]# cd /root/go/src/github.com/libopenstorage/openstorage/
[root@manager1-docker openstorage]# $GOPATH/bin/osd -d -f etc/config/config.yaml
INFO[0000] OSD enabling cluster mode.
INFO[0000] Starting REST service on socket : /var/lib/osd/cluster/osd.sock
INFO[0000] Starting volume driver: nfs
INFO[0000] NFS driver initializing with 192.168.174.210:/nfs-server
INFO[0000] NFS initialized and driver mounted at:  /var/lib/openstorage/nfs/
INFO[0000] Starting REST service on socket : /var/lib/osd/driver/nfs.sock
INFO[0000] Starting REST service on socket : /run/docker/plugins/nfs.sock
INFO[0000] Cluster manager starting...
INFO[0000] Cluster is uninitialized...
INFO[0000] Initializing a new cluster.
INFO[0000] Node 1 joining cluster...
INFO[0000] Cluster ID: deadbeeef
INFO[0000] Node Mgmt IP: 192.168.174.210
INFO[0000] Node Data IP: 192.168.174.210
INFO[0000] Cluster manager starting watch at version 5
INFO[0000] Waiting for the cluster to reach quorum...
INFO[0000] Starting Gossip...
INFO[0002] Cluster db snapshot at: 7
INFO[0002] Starting collector watch at 7
INFO[0002] Cluster is uninitialized...
**PANI[0002] Fatal, Unable to find self node entry in local cache**
panic: (*logrus.Entry) (0x1201e60,0xc820300180)

goroutine 1 [running]:
panic(0x1201e60, 0xc820300180)
        /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/libopenstorage/openstorage/vendor/github.com/Sirupsen/logrus.Entry.log(0xc82000a4c0, 0xc820302210, 0x0, 0x0, 0x0, 0xc820302100, 0x0, 0x0, 0x0, 0xc820300140, ...)
        /root/go/src/github.com/libopenstorage/openstorage/vendor/github.com/Sirupsen/logrus/entry.go:113 +0x62c
github.com/libopenstorage/openstorage/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc82012e518, 0xc82012e4a8, 0x1, 0x1)
        /root/go/src/github.com/libopenstorage/openstorage/vendor/github.com/Sirupsen/logrus/entry.go:158 +0x99
github.com/libopenstorage/openstorage/vendor/github.com/Sirupsen/logrus.(*Entry).Panicln(0xc82012e518, 0xc82014fc40, 0x1, 0x1)
        /root/go/src/github.com/libopenstorage/openstorage/vendor/github.com/Sirupsen/logrus/entry.go:253 +0x120
github.com/libopenstorage/openstorage/vendor/github.com/Sirupsen/logrus.(*Logger).Panicln(0xc82000a4c0, 0xc82014fc40, 0x1, 0x1)
        /root/go/src/github.com/libopenstorage/openstorage/vendor/github.com/Sirupsen/logrus/logger.go:210 +0xe7
github.com/libopenstorage/openstorage/vendor/go.pedge.io/dlog/logrus.(*logger).Panicln(0xc8200be820, 0xc82014fc40, 0x1, 0x1)
        <autogenerated>:85 +0x6d
github.com/libopenstorage/openstorage/vendor/go.pedge.io/dlog.Panicln(0xc82014fc40, 0x1, 0x1)
        /root/go/src/github.com/libopenstorage/openstorage/vendor/go.pedge.io/dlog/dlog.go:210 +0x49
github.com/libopenstorage/openstorage/cluster.(*ClusterManager).joinCluster(0xc820226000, 0xc8202260d0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/libopenstorage/openstorage/cluster/manager.go:465 +0x9cb
github.com/libopenstorage/openstorage/cluster.(*ClusterManager).waitForQuorum(0xc820226000, 0x0, 0x0, 0x0)
        /root/go/src/github.com/libopenstorage/openstorage/cluster/manager.go:736 +0xd3
github.com/libopenstorage/openstorage/cluster.(*ClusterManager).Start(0xc820226000, 0x0, 0x19df600, 0x0, 0x0)
        /root/go/src/github.com/libopenstorage/openstorage/cluster/manager.go:972 +0x81b
main.start(0xc8201dc640, 0x0, 0x0)
        /root/go/src/github.com/libopenstorage/openstorage/cmd/osd/main.go:234 +0x19b8
main.wrapAction.func1(0xc8201dc640)
        /root/go/src/github.com/libopenstorage/openstorage/cmd/osd/main.go:253 +0x29
github.com/libopenstorage/openstorage/vendor/github.com/codegangsta/cli.(*App).Run(0xc820198840, 0xc82000a240, 0x4, 0x4, 0x0, 0x0)
        /root/go/src/github.com/libopenstorage/openstorage/vendor/github.com/codegangsta/cli/app.go:201 +0x13ce
main.main()
        /root/go/src/github.com/libopenstorage/openstorage/cmd/osd/main.go:127 +0x12e6

Why appears error "Fatal, Unable to find self node entry in local cache"?

I think the config.yaml file is correct for my environment:
[root@manager1-docker openstorage]# cat etc/config/config.yaml
---

osd:
  cluster:
    nodeid: "1"
    clusterid: "deadbeeef"
  drivers:
    nfs:
      server: "192.168.174.210"
      path: "/nfs-server"
  graphdrivers:

Where is the problem?

Regards.

Juan Carlos Molinos

**Comment by adityadani** [comment]
Thanks @jcmolinos for pointing this out.
We have fixed the issue. Can you pull the latest code/docker osd image and try it out?
