### ISSUE TITLE
Use golang 1.5 compatible vendoring?

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#18]
https://golang.org/s/go15vendor

The Dockerfile already uses golang 1.5, and vendoring will be this standard going forward, so since this is a newish project (and Godeps has a ton of recursive problems as it is, ie if I use openstorage as a library), maybe enforce this?

If `GO15VENDOREXPERIMENT` is set in golang 1.5, then godep respects it.

We do this in github.com/pachyderm/pachyderm.

**Comment by jvinod** [comment]
SGTM - will our build process change?

**Comment by peter-edge** [comment]
No, but I can help out additionally with that, I've been dealing with this for a bit.

The only thing you need is to have `export GO15VENDOREXPERIMENT=1` pretty much anywhere. If all the tests are in docker, you can just have this in the Dockerfile. For the Makefile, you can export it too.
