### ISSUE TITLE
introduce and API Call similar to pxctl volume list 

### ISSUE THREAD

**Issue by calvarado2004** [libopenstorage/openstorage#2020]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:

**What you expected to happen**:

We see that the volume list option just returns a list of the volumes by portworx volume name. I was hoping to get a result similar to pxctl v l. This includes pwx volume name, the pv name and the attached/detached state. That would allow us to read in the detached volumes that we are interested in in a single pass and then dip down to the next level to look at the inspect option for the volumes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lpabon** [comment]
Hi @calvarado2004 , we have [EnumerateWithFilters](https://libopenstorage.github.io/w/release-9.2.generated-api.html#methodopenstorageapiopenstoragevolumeenumerate) which returns the volume ids, then for each volume you can run [Inspect](https://libopenstorage.github.io/w/release-9.2.generated-api.html#methodopenstorageapiopenstoragevolumeinspect). Or you can also call one function to get this info: [InspectWithFilters](https://libopenstorage.github.io/w/release-9.2.generated-api.html#methodopenstorageapiopenstoragevolumeinspectwithfilters)
