### ISSUE TITLE
Remove Travis GitHub Integration :)

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#22]
All PRs are shown as failing :)

**Comment by jvinod** [comment]
we're hoping to make that work, we can nuke it till we get it to work..

**Comment by peter-edge** [comment]
Will send you a PR about that if you want - do you do any mounts
specifically with btrfs?

**Comment by jvinod** [comment]
PR sounds good. Thanks.
In the btrfs_test.go, the test setup was going to mount btrfs from a file - not there yet.

**Comment by peter-edge** [comment]
All the cloud CI providers disable mounting, or don't have btrfs version
3.12 or above, I'll save you a lot of time, I tried (circle, Travis,
shippable, etc).

We went with our own using buildkite.

**Comment by jvinod** [comment]
Hmm..how do they disable mounting a file as a loopback device?

**Comment by peter-edge** [comment]
Maybe I did something wrong - would you be willing to send me what you
think would work, I'm happy to try it out with a setup I already have.

**Comment by jvinod** [comment]
sure I just meant an equivalent of : 
#touch foo
# truncate foo --size 1G
# mkfs.btrfs foo
# mkdir /mnt/foo; mount -t btrfs foo /mnt/foo

**Comment by peter-edge** [comment]
https://github.com/pachyderm/pachyderm/tree/master/etc/btrfs

Had the same thing (except for -t, but this shouldn't be relevant)

http://blog.circleci.com/sudo-circleci-make-me-a-sandwich/ came the closest.

Travis is way too out of date in terms of their legacy infrastructure (which is the only thing that can run sudo anyways).

**Comment by jvinod** [comment]
I see - I guess your first comment to the effect "we shouldn't bother with Travis integration because this won't work anyhow?"  

https://travis-ci.org/libopenstorage/openstorage

**Comment by peter-edge** [comment]
If you exclude btrfs tests, travis may be fine, on the legacy infrastructure. The btrfs version on the legacy infrastructure is something around 0.9 however.

**Comment by peter-edge** [comment]
Over on https://github.com/libopenstorage/openstorage/pull/21 though, I'm working on getting `make docker-test` to pass, you may have more insight there.

**Comment by jvinod** [comment]
make test should work now. aws driver  test needs work though..

**Comment by peter-edge** [comment]
Yep :) Can we do this though, heh :)

**Comment by jvinod** [comment]
ping @ankitgd  - could you blow away the travis-ci integ :)

**Comment by peter-edge** [comment]
I promise to help setup something cool soon :)

**Comment by peter-edge** [comment]
Adding @sr who set up Buildkite for us at Pachyderm recently

**Comment by sr** [comment]
The buildkite model is great for projects like this since it gives complete control over the build machines. All that's needed is a machine running the agent which works pretty much everywhere:

https://buildkite.com/docs/agent/installation

This is the ansible playbook we use to configure the CI machines at Pachyderm:

https://github.com/pachyderm/pachyderm/blob/master/etc/ops/ansible/playbooks/ci.yml

There might be one or two assumptions in there that are specific to our setup (Ubuntu vivid VMs running on Google Cloud) but we should be able to make this work for openstorage stuff fairly easily.

**Comment by jvinod** [comment]
Cool, look forward to buildkite. 

@ankitgd blew away travis credentials  - a new dummy  PR https://github.com/libopenstorage/openstorage/pull/42  doesn't show those tests failing anymore.

**Comment by peter-edge** [comment]
Closing :)
