### ISSUE TITLE
Organize api/server unit tests

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#299]
**Is this a BUG REPORT or FEATURE REQUEST?**:
*feature*

We should organize all the `api/server/XXX_test.go` utility functions into a single file. Either a new file called `testutils_test.go` or into `cluster_test.go`.

Here are the objects that need to be organized:

* `testCluster` from https://github.com/libopenstorage/openstorage/blob/master/api/server/cluster_test.go#L20
* `testServer` and `setupMockDriver` from https://github.com/libopenstorage/openstorage/blob/master/api/server/creds_test.go#L27
* `Setup` which should be called `testRestServer` from https://github.com/libopenstorage/openstorage/blob/master/api/server/creds_test.go#L67

**Comment by ipochi** [comment]
PR #307  to address this.
