### ISSUE TITLE
client/client_test.go references btrfs

### ISSUE THREAD

**Issue by gourao** [libopenstorage/openstorage#3]
It should reference a null driver and not an actual driver to avoid driver dependancies in the top level framework.

**Comment by peter-edge** [comment]
Still relevant?

**Comment by jvinod** [comment]
Not really. Client test now references the nfs driver with "" server (defaulting to vfs). We should just move this to use the vfs driver.

**Comment by peter-edge** [comment]
Can we close this then? :)

**Comment by gourao** [comment]
Yes.
