### ISSUE TITLE
Migrate dlog 

### ISSUE THREAD

**Issue by jvinod** [libopenstorage/openstorage#310]
dlog is no longer maintained, author recommends to migrate to https://github.com/uber-go/zap:

**Comment by lpabon** [comment]
I prefer not moving to zap since there is no need for speed in openstorage. My suggestion is to use the standard Kubernetes simple logger https://github.com/golang/glog .

We can also discuss changing dlog to logrus, but my vote is for glog.

**Comment by lpabon** [comment]
After some discussion (offline) the idea is to use logrus.

**Comment by peter-edge** [comment]
Glog was never meant to be a standard logger for Golang, and is not recommended, even by Google anymore. Logrus is very slow, and a lot of people are moving away from it. The author also does things like change the import path. Zap has kind of become a new standard.

**Comment by lpabon** [comment]
Cool, then we will change to it when it comes part of golang.

**Comment by lpabon** [comment]
Closed by #363
