### ISSUE TITLE
NFS driver accepts blank volume names when creating volume using REST endpoint

### ISSUE THREAD

**Issue by ipochi** [libopenstorage/openstorage#321]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
NFS driver allows to create with blank volume name or double-spaces or n-spaces volume names when using the REST endpoint.
ex : "" , " " , "   " , "    " -> all of the mentioned are created when created using REST endpoint
**What you expected to happen**:
Expect an error to the user that blank names are not valid volume names.
**How to reproduce it (as minimally and precisely as possible)**:
Make a rest call to create endpoint with the volume name set as blank
**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by timbouvier** [comment]
@ipochi I see what you're saying for volume names that are space characters. For the empty string though I see random hash being assigned as volume name. Do you see something different?

Also volume names like "test volume" are valid with nfs driver. I think error should be thrown if volume name contains any space character. Any other special characters you think should be invalid?

**Comment by timbouvier** [comment]
@ipochi Actually I see the issue with empty string as well now when I curl directly at the unix socket

**Comment by ipochi** [comment]
@timbouvier no hash , see the output of enumerate [name and id are set as blank as that was provided to it by me]
`[{
 "id": "",
 "source": {
  "parent": "",
  "seed": ""
 },
 "readonly": false,
 "locator": {
  "name": "",
`
I think volume name could be okay with what user provides inside quotes [double check needed on allowed special chars] , but i believe id should not the same as name

right now , when i create a volume with name "a b c" , the id as gets the same "a  b c"

**Comment by timbouvier** [comment]
@ipochi Okay makes sense. In terms of the the create request I don't see "id" being used anywhere / just "name". Also wouldn't name=id help prevent confusion against volumes with the same name?

```go
// VolumeCreateRequest is a structure that has the locator, source and spec
// to create a volume
// swagger:model
type VolumeCreateRequest struct {
        // User specified volume name and labels
        Locator *VolumeLocator `protobuf:"bytes,1,opt,name=locator" json:"locator,omitempty"`
        // Source to create volume
        Source *Source `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
        // The storage spec for the volume
        Spec *VolumeSpec `protobuf:"bytes,3,opt,name=spec" json:"spec,omitempty"`
}
``` 

```go
// VolumeLocator is a structure that is attached to a volume
// and is used to carry opaque metadata.
// swagger:model
type VolumeLocator struct {
        // User friendly identifier
        Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
        // A set of name-value pairs that acts as search filters
        VolumeLabels map[string]string `protobuf:"bytes,2,rep,name=volume_labels,json=volumeLabels" json:"volume_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=valu\
e"`
}
```

**Comment by ipochi** [comment]
@timbouvier  id is generated using uuidgen or anything similar depending on the volume driver implementation [checkout volume/drivers/buse] for example. NFS driver doesn't do that.

**Comment by timbouvier** [comment]
@ipochi okay got it. I'll submit a PR
