### ISSUE TITLE
Error information is not correctly retrieved by the golang client

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#372]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
See: https://github.com/libopenstorage/openstorage/pull/350/files#diff-7d1e2910f3cef1ae679f6a61d7b7325cR211 in #350 

The issue is that the function parseHTTPstatus is expecting the error string to be encoded in the body as a `Status` Json object. The issue is that some, or most, of the handlers in the server the function sendError() which in turn uses `http.Error(w, err)` to write the error as a raw string in the body.

With the error being raw string, parseHTTPstatus currently does not retreive the error correctly and thus it returns the generic `HTTP xxxx status`.

**What you expected to happen**:
The client functions to return the error string set by the server handler.

**Proposals**:

1. Support both a status json object, or fall back to reading the string and returning it if length is != 0
2. Standardize on the status type for ALL OSD api calls

My vote is for number 1 now and number 2 for next release.

**Comment by pault84** [comment]
```
