### ISSUE TITLE
Configuration library be exposed over REST?

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#383]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Question

**What happened**:
Should the configuration library be exposed over REST? That would mean that anyone with the REST client can manipulate metadata in the configuration. This may lead to many issues.

**Comment by sdeoras** [comment]
@lpabon : FYI, we did discuss this topic a few times already and have implemented both methods to interface with osdconfig, one via REST and other directly through kvdb. I believe you _do_ want users to be able to change a few params, which was the original intent that @harsh-px brought to me a few times. I would like to know which parameters are sensitive.

**Comment by sdeoras** [comment]
closing this per internal discussion (PWX-5154)
