### ISSUE TITLE
SDK Rest endpoints look wrong

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#452]
**Is this a BUG REPORT or FEATURE REQUEST?**:
DISCUSSION

**What happened**:
As part of #449 @disrani-px brought up the following:

> These endpoints look wrong, it should look like the current endpoints and you shouldn't need a different type of endpoint for each type of cloud.
> For creating POST to /v1/credential (The input object should have the type and corresponding config)
> For listing GET from /v1/credential
> For getting a particular credential GET from /v1/credential/{id}
> For deleting DELETE from /v1/credential/{id}

Placing it here for an open discussion

**Comment by lpabon** [comment]
Currently the SDK REST points are a gateway to the gRPC SDK Server, where all RPC handlers require objects for requests, that is why I used POST for all, but I can understand it may look weird. This is also done by [etcd's proto file](https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto). 

Let's take a look at GET for example. On GETs normally data is not sent to the server, so that would look weird also.

On the other hand, I believe we can change some of the delete calls to use the DELETE method by submitting data instead of using the URL. That seems like a possibility.

So I would suggest having only POST and DELETE.

**Comment by disrani-px** [comment]
Etcd's proto file also looks wrong, we shouldn't base our protos on wrong examples.

Basic info about REST APIs: http://www.restapitutorial.com/lessons/httpmethods.html
Some good examples from Google's Service gRPCs: https://cloud.google.com/service-management/reference/rpc/google.api#http (notice the GETs pass in messages)

It is very common to pass in data during GETs too. The type of operation doesn't not enforce whether you can pass in data or not.

**Comment by lpabon** [comment]
Ok, we'll try this out.

For tracking purposes:
Part of #407.
