### ISSUE TITLE
OSD should understand specific labels

### ISSUE THREAD

**Issue by coozy** [libopenstorage/openstorage#48]
Right now, labels can be passed down to the drivers.  Having special or specific labels that mean specific things will help standardize all drivers and provide a known way to pass properties down to the drivers while provisioning volumes.

For example, having a specific label such as one for a `class of service` will prevent different drivers from having different labels for the same purpose.

**Comment by kunalkushwaha** [comment]
By labels you mean labels as driver attributes or labels for volume?

**Comment by coozy** [comment]
@kunalkushwaha  Labels as driver attributes

**Comment by kunalkushwaha** [comment]
@coozy I think, its better to have such attributes with volumes rather then driver.
As osd driver/docker volume plugins, enable the storage availability to container, but they themselves are not storage controller.

for example. A driver like btrfs, ``storage class`` or ``QoS`` attributes depends on how it is assisted with physical infrastructure like SSD, fast disk, SAN or slow disks.    
So I think it make more sense to have such attributes with volume.

For volume, in OSD labels are supported. With #7, Docker passed labels can be set to OSD volumes.

**Comment by gourao** [comment]
Closing this issue as we don't have enough of an opinion on changing how the labels are used right now.
