### ISSUE TITLE
Need a REST interface to expose the underlying storage system capabilities

### ISSUE THREAD

**Issue by gourao** [libopenstorage/openstorage#49]
Apcera @earlruby  would like an interface to be able to query the underlying node capabilities in terms of storage performance so that the container placement decisions can be influenced.

**Comment by jupiturliu** [comment]
@gourao would be great to not only know the hardware performance, but also like to know the host performance including IOPS,CPU utilization, throughput, latency etc.

**Comment by gourao** [comment]
This is being addressed by a separate project and openstorage can use that when it is available.
