### ISSUE TITLE
Suggestion: Design discussion.

### ISSUE THREAD

**Issue by kunalkushwaha** [libopenstorage/openstorage#5]
Hi,

I am really interested in this project, and would like to contribute.
But I cant see any discussion on this forum. It will be great to have design & development discussion on github, so anyone interested from outside team can easily pickup.

**Comment by jvinod** [comment]
@kunalkushwaha Thanks for the feedback. That is the direction we're headed, you will see a lot more discussion here going forward and would appreciate your contributions.

**Comment by gourao** [comment]
@kunalkushwaha, Agreed.  I think a good place to start would be to get some feedback and discussion going on the [API](https://github.com/libopenstorage/specs/tree/master/api).  Did you have a particular area of interest to start a discussion on?

**Comment by kunalkushwaha** [comment]
@jvinod @gourao Thanks for you reply. 

Yeah, apart from API usage, I would also like to understand, current state of integration with swarm. I saw one discussion going on for volume support https://github.com/docker/swarm/issues/1189
But it is still not concluded and Interfaces are not implemented yet.

In openstorage code, https://github.com/libopenstorage/openstorage/blob/master/api/server/docker.go looks like docker volume plugin integration.

**Comment by jvinod** [comment]
We are currently working on supporting https://github.com/docker/docker/pull/14242 before we move onto swarm. Would you be interested in contributing to openstorage support for  https://github.com/docker/docker/pull/14242 ? Thanks!

**Comment by kunalkushwaha** [comment]
Thanks for suggesting this.  Yeah I would like to work on this.

**Comment by jvinod** [comment]
closing this..
