### ISSUE TITLE
Volume security

### ISSUE THREAD

**Issue by kunalkushwaha** [libopenstorage/openstorage#50]
Should there be some authentication mechanism in place to connect docker with docker volumes providers/Drivers?

- If not using storage which requires some kind of auth key etc (aws s3, ceph etc), volumes can be accessed by anyone, who knows the driver/storage providers available.

**Comment by jupiturliu** [comment]
@kunalkushwaha any updates in this regard?

**Comment by kunalkushwaha** [comment]
It is open question to openstorage maintainers/community. I think @jvinod @gourao may share their views.

**Comment by gourao** [comment]
It's been a feature people have asked for.  Need to prioritize and schedule it's implementation.

**Comment by gourao** [comment]
Closing .. will reopen with a roadmap item
