### ISSUE TITLE
404 Failed to locate volume

### ISSUE THREAD

**Issue by yoanisgil** [libopenstorage/openstorage#51]
I'm seeing this whenever I run `docker volume ls` or `docker volume rm`:

```
WARN[0009] 404 Failed to locate volume: Cannot locate volume test  Driver=nfs ID=test Request=remove
```

I think I can fairly reproduce this issue:

- Launch `osd` with: `/usr/local/bin/osd -d  -f /usr/local/etc/osd.yml`
- Create a new volume: `docker volume create --driver=nfs --name=test1`
- Stop the daemon with Ctrl+C
- Relaunch `osd` with:`/usr/local/bin/osd -d  -f /usr/local/etc/osd.yml`
- Run `docker volume ls` or `docker volume rm test1`

I'm running:

```bash 
$ osd --version
osd version 0.3

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
```

Config file is:

```yml
osd:
  drivers:
      nfs:
        server: "10.1.8.43"
        path: "/home/sites/configurations"
```

**Comment by gourao** [comment]
Hi @yoanisgil  - This is because you have not specified a key/value database for the OSD to use.

By default OSD will use an in memory ephemeral DB.  So volumes created will be lost across restarts.

To use a persistent key/value DB such as ETCD, specify the URL via the `--kvdb` option.

I suppose the README should document this.

**Comment by yoanisgil** [comment]
@gourao thanks! Is consul supported? You probably use libkv but I just wanted to check.

**Comment by yoanisgil** [comment]
Well,  looks like is not :(. It would be nice thought to support consul or any other backend support by Swarm, probably using https://github.com/docker/libkv. Anyhow, I will go with etcd for the moment.

**Comment by gourao** [comment]
It seems pretty easy to use `libkv`.  I'll take a look at swapping to it.

**Comment by yoanisgil** [comment]
Thanks! That will be a valuable addition since it will make things easier for those using Swarm ;)

**Comment by yoanisgil** [comment]
@gourao I am running OSD on 3 nodes (the goal is to have persistent volumes on top of a Swarm cluster). I am running osd like this:

`/usr/local/bin/osd -d -f /usr/local/etc/osd.yml --kvdb etcd-kv://aws034:4001`

and I was expecting that when creating a volume on `node1` it should then be listed on `node2` with `docker volume ls`. Isn't that the expect result?

**Comment by jvinod** [comment]
@yoanisgil 'docker volume ls'  should work seamlessly with swarm pending 'https://github.com/docker/swarm/issues/1189' - if you use 'osd <driver_name> enumerate/inspect' that will  display cluster wide persistent volumes. There is also work being done for docker to directly query the volume plugin api to ls volumes - this would make it persistent across docker restarts which it currently is not.

**Comment by gourao** [comment]
Hey @yoanisgil 
I just checked in support for consul.  I did very basic testing on it, but it seems to work for me. 

Run it as
```osd -d -f config.yaml --kvdb=consul-kv://localhost:8500```

I could not use `libkv` as is because OSD has other extensions it uses and the KVDB it currently uses supports transactions.

In any event, try this out and see if it works.

**Comment by yoanisgil** [comment]
All right! Will take a look at let you know.

**Comment by gourao** [comment]
Closing since consul support is in.
