### ISSUE TITLE
sdk: Enumerate calls should be GET calls

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#539]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
The SDK Enumerate calls should be GETs. For this to correctly occur, we need the following:

* Enumerate calls changed to GET
* new APIs called EnumerateWithFilters() to use POST

**What you expected to happen**:
Some SDK Enumerate calls are PUT/POST because they can pass in maps. The gRPC REST Gateway code generator does not allow GETs to pass data.

**Comment by jsilberm** [comment]
Well in keeping with not violating the Principal of Least Astonishment.
As an API user/consumer, the first calls I'd try to make when hitting an API for a product like this would be "GET volumes", GET volumes/volumeID", "GET nodes", "GET nodes/nodeID".
