### ISSUE TITLE
Openstorage compling errors

### ISSUE THREAD

**Issue by jupiturliu** [libopenstorage/openstorage#54]
Following instructions but still got below errors:
Got below errors when I am trying to give a try to openstorage

go get -d github.com/libopenstorage/openstorage/...
# cd /home/jupiturliu/tmp/src/github.com/libopenstorage/openstorage; git pull --ff-only
From https://github.com/libopenstorage/openstorage
 * [new branch]      master     -> origin/master
 * [new branch]      proto      -> origin/proto
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

**Comment by jvinod** [comment]
@jupiturliu - we require go 1.5

The build  instructions (https://github.com/libopenstorage/openstorage#installing-dependencies) was modified to reflect that (note the GO15VENDOREXPERIMENT=1 which is required)
```
$ GO15VENDOREXPERIMENT=1 go get -d github.com/libopenstorage/openstorage/...
$ $GOPATH/src/github.com/libopenstorage/openstorage $ make install
```

1) are you running go 1.5  (output of `go version`) 
2) Is the error that you pasted the output  of "GO15VENDOREXPERIMENT=1 go get -d github.com/libopenstorage/openstorage/..."?

**Comment by jupiturliu** [comment]
Hi 
   Problem was resolved. Forgot to put GO15VENDOREXPERIMENT=1 in front of go get.

   thanks,
   James
