### ISSUE TITLE
btrfs compile error

### ISSUE THREAD

**Issue by jupiturliu** [libopenstorage/openstorage#55]
# github.com/libopenstorage/openstorage/vendor/github.com/docker/docker/daemon/graphdriver/btrfs
vendor/github.com/docker/docker/daemon/graphdriver/btrfs/btrfs.go:8:25: fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
                         ^
compilation terminated.
make: *** [install] Error 2

**Comment by jvinod** [comment]
@jupiturliu  You need the following packages installed.
btrfs-progs-devel-3.16.2-1.el7.x86_64 
btrfs-progs-3.16.2-1.el7.x86_64

In the absence of that you can do a `make docker-build`
I also checked in conditional compilation for btrfs if you don't have the packages installed. So if you get the latest, you should be able to build without the btrfs packages.

Thanks

**Comment by jupiturliu** [comment]
Since my OS is ubuntu 14.04, the package that should install is btrfs-tools. thanks
