### ISSUE TITLE
Require new fields in osdconfig to enable consul TLS connection

### ISSUE THREAD

**Issue by sdeoras** [libopenstorage/openstorage#557]
**Is this a BUG REPORT or FEATURE REQUEST?**:
This is a bug report

**What happened**:
We wish to enable TLS for consul client connection. In order to use TLS, consul requires three new inputs that are currently not accommodated in the kvdb config struct defined at: https://github.com/libopenstorage/openstorage/blob/master/osdconfig/struct.go#L29

**What you expected to happen**:
Three new fields need to be added to the kvdb struct.

```
// CAAuthAddress is the address of CA signing authority (required in consul TLS config)
CAAuthAddress string
// InsecureSkipVerify has a value true or false (required in consul TLS config)
InsecureSkipVerify bool
// TransportScheme points to http transport being either http or https.
TransportScheme string
```

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
TransportScheme will have a value of http or https. While we are currently inferring this value in the code based on consul end point address provided by the user, an entry for this field in the struct is probably a good idea since it provides completion to everything we need in order to establish consul connection with or without TLS. So I recommend we add it, but I am open to skipping it as well based on discussions.

**Environment**:
- Container Orchestrator and version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lpabon** [comment]
@sdeoras I think these should be defined just for Consul since these values are only used to connect to that server (OSD being the client), right?

**Comment by sdeoras** [comment]
yes, correct, these are only to be used for consul. it may break a lot of things if we try to split the kvdb config struct into three parts:

- common
- etcd and
- consul

certainly easier if we add to existing struct. @adityadani what are your thoughts?

**Comment by lpabon** [comment]
Ok, I see. Should be be more of a KVDB discussion? Then osdconfig is just the consumer of that, right? So to keep everything compatible, I feel what you have proposed is correct.

**Comment by sdeoras** [comment]
ok cool. i'll send out a PR shortly.
