### ISSUE TITLE
OSD start failed in Ubuntu 14.04

### ISSUE THREAD

**Issue by jupiturliu** [libopenstorage/openstorage#58]
sudo /home/jupiturliu/work/bin/osd -d -f config.yaml 
INFO[0000] Starting volume driver: nfs                  
INFO[0000] NFS driver initializing with 127.0.0.1:/nfs  
INFO[0000] Unable to mount 127.0.0.1:/nfs at /var/lib/openstorage/nfs/ (permission denied) 
WARN[0000] Unable to start volume driver: nfs, permission denied 
jupiturliu@jupiturliu:~/work/src/github.com/libopenstorage/openstorage$ sudo /home/jupiturliu/work/bin/osd -d -f config.yaml 
INFO[0000] Starting volume driver: buse                 
INFO[0000] BUSE initializing in clustered mode          
INFO[0000] Adding cluster event listener: buse          
INFO[0000] BUSE initialized and driver mounted at:  /var/lib/openstorage/buse/ 
INFO[0000] Starting REST service on /var/lib/osd/driver/buse.sock 
INFO[0000] Starting REST service on /run/docker/plugins/buse.sock 
INFO[0000] Starting volume driver: nfs                  
INFO[0000] NFS driver initializing with 127.0.0.1:/nfs  
INFO[0000] Unable to mount 127.0.0.1:/nfs at /var/lib/openstorage/nfs/ (permission denied) 
WARN[0000] Unable to start volume driver: nfs, permission denied

**Comment by gourao** [comment]
can you make sure you have `no_root_squash` enabled on your local NFS server...

```
/nfs *(rw,sync,no_root_squash)
```

**Comment by jupiturliu** [comment]
Problem solved, the no_root_squash should be added over there. Would be great if we have everything in the doc.

INFO[0000] Starting REST service on /var/lib/osd/driver/nfs.sock 
INFO[0000] Starting REST service on /run/docker/plugins/nfs.sock 
INFO[0000] Starting volume driver: buse                 
INFO[0000] BUSE initializing in clustered mode          
INFO[0000] Adding cluster event listener: buse          
INFO[0000] BUSE initialized and driver mounted at:  /var/lib/openstorage/buse/ 
INFO[0000] Starting REST service on /var/lib/osd/driver/buse.sock 
INFO[0000] Starting REST service on /run/docker/plugins/buse.sock 
INFO[0000] Starting graph driver: proxy                 
INFO[0000] Starting REST service on /run/docker/plugins/proxy.sock 
INFO[0000] Starting graph driver: layer0                
INFO[0000] Starting REST service on /run/docker/plugins/layer0.sock 
INFO[0000] Cluster manager starting...                  
INFO[0000] Cluster is uninitialized...                  
INFO[0000] Will initialize a new cluster.               
INFO[0003] Node 1 joining cluster... 
	Cluster ID: deadbeeef
	IP: 10.0.2.15 
INFO[0003] Cluster database updated.

**Comment by gourao** [comment]
Cool.  You have a fresh set of eyes... if you can suggest in a PR what the
changes should be to the doc, that would be great for others

**Comment by jupiturliu** [comment]
Sure thing, I would put what I get through in a FAQ doc. Hopfully it would be helpful for new folks like me to get through and start the service properly.
