### ISSUE TITLE
docker run failed without config.yaml in the /etc

### ISSUE THREAD

**Issue by jupiturliu** [libopenstorage/openstorage#59]
docker run \
		--privileged \
		-v /home/jupiturliu/work/src/github.com/libopenstorage/openstorage:/etc \
		-v /usr/share/docker/plugins:/usr/share/docker/plugins \
		-v /var/lib/osd/driver:/var/lib/osd/driver \
		-v /mnt:/mnt \
		openstorage/osd -d -f /etc/config.yaml
no such file or directory
Error response from daemon: Cannot start container 346e697283af3b4104e7cce0b1aea71c21798c64717167065c8fd81b8fe5f639: [8] System error: no such file or directory
make: *** [launch] Error 1

**Comment by gourao** [comment]
This can actually be reproduced by running 
```
docker run --privileged openstorage/osd -d -f config.yaml 
no such file or directory
Error response from daemon: Contained command not found or does not exist.
```

@jupiturliu we are looking at it.

**Comment by jvinod** [comment]
@jupiturliu  it should work now - thanks for reporting this! However, please continue to use osd standalone, outside the container while we iron out some mount propagation problems.

**Comment by jupiturliu** [comment]
Hi 
   It run with different result. It does not pop  out error any more . However, after the container launched, I just used the docker ps to check the status of container, I did not find anything related to osd on container . Am I missing anything?

Regards,
James

 
docker run \
		--privileged \
		-d \
		-v /home/jupiturliu/work/src/github.com/libopenstorage/openstorage:/etc \
		-v /run/docker/plugins:/run/docker/plugins \
		-v /var/lib/osd/:/var/lib/osd/\
		openstorage/osd -d -f /etc/config.yaml
0588a1477e112e6a4a6e37276d503660394626ba7b9dc25c6b2f4f23b66dff2a

**Comment by jvinod** [comment]
@jupiturliu  do you have the output of `docker logs 0588a1477e112e6a4a6e37276d503660394626ba7b9dc25c6b2f4f23b66dff2a`

**Comment by jupiturliu** [comment]
@jvinod since the fuse driver of graph driver was updated, the compilation is broken.

# github.com/libopenstorage/openstorage/graph/drivers/fuse
graph/drivers/fuse/fuse.c:12:18: fatal error: fuse.h: No such file or directory
 #include <fuse.h>
                  ^
compilation terminated.
Makefile:68: recipe for target 'docker-build-osd-internal' failed
make: *** [docker-build-osd-internal] Error 2
make: *** [docker-build-osd] Error 2

I do install the libfuse2 in the ubuntu. Any clues?

Regards,
James

**Comment by jvinod** [comment]
I checked in conditional compilation for fuse - it is experimental, not to be used currently. Thanks

**Comment by jupiturliu** [comment]
thanks, the error is out.

**Comment by peter-edge** [comment]
Hey @gourao @jvinod why did you make this golang:1.5.1 base?

**Comment by jvinod** [comment]
It didn't work with the original dockerfile - see the description of the bug.

**Comment by gourao** [comment]
Closing
