### ISSUE TITLE
Performanc Bench

### ISSUE THREAD

**Issue by jupiturliu** [libopenstorage/openstorage#60]
Hi 
   Is there any benchmark can run for certainer applications like NoSql database or Sql database?

   Regards,
   James

**Comment by gourao** [comment]
We usually run `fio`.  Pinging @ankitgd for more details.

**Comment by jupiturliu** [comment]
@ankitgd would be possible to have the benchmark setup guidance ? Then I can  have a chance to run the benchmark if possible.

**Comment by gourao** [comment]
We just run `fio` against the exposed volumes.  The results depend on the underlying hardware, but I'd recommend to run that.

**Comment by jupiturliu** [comment]
@gourao how do you run fio? Do you run fio inside of container?

**Comment by gourao** [comment]
I run it at the host - It should not matter how you run fio.

**Comment by jvinod** [comment]
Yes we run fio as well as real app work load generation e.g. sysbench.  We run them both at the host directly on the volumes as well as in containers. We're also going to run these  benchmark tools on a daily basis against openstorage and will make them available for anyone who wishes to run benchmarks.

**Comment by jupiturliu** [comment]
@jvinod sounds great. thanks.Are you able to share the fio plugin to run the performance bench against the volume? thanks.

**Comment by gourao** [comment]
Here is an example of running fio from Docker...

```
docker run --rm ankitgd/fio_drv --blocksize=4k-64k --ioengine=libaio --readwrite=randrw --size=50% --filesize=1M-10M --name=test --verify=md5 --time_based --direct=1 --gtod_reduce=1 --iodepth=1 --randrepeat=1 --rwmixread=75 --nrfiles=300
```
