### ISSUE TITLE
make update-test-deps failed

### ISSUE THREAD

**Issue by jupiturliu** [libopenstorage/openstorage#61]
Fetching https://bazil.org/fuse?go-get=1
https fetch failed.
import "bazil.org/fuse": https fetch: Get https://bazil.org/fuse?go-get=1: dial tcp: lookup bazil.org on 127.0.1.1:53: no such host
package bazil.org/fuse: unrecognized import path "bazil.org/fuse"
Fetching https://bazil.org/fuse/fs?go-get=1
https fetch failed.
import "bazil.org/fuse/fs": https fetch: Get https://bazil.org/fuse/fs?go-get=1: dial tcp: lookup bazil.org on 127.0.1.1:53: no such host
package bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"

**Comment by gourao** [comment]
Their site is down at the moment :(

Let's try in a bit again - I am getting the same error.

@jvinod `bazil` moved their code to github, we should probably switch to that.

**Comment by jvinod** [comment]
ping @peter-edge

**Comment by peter-edge** [comment]
The import path is still locked to bazil.org:

https://github.com/bazil/bazil/blob/master/doc.go

This means it has to be bazil.org/bazil:

https://golang.org/s/go14customimport

```
$ go get -v bazil.org/bazil
Fetching https://bazil.org/bazil?go-get=1
Parsing meta tags from https://bazil.org/bazil?go-get=1 (status code 200)
get "bazil.org/bazil": found meta tag main.metaImport{Prefix:"bazil.org/bazil", VCS:"git", RepoRoot:"https://github.com/bazil/bazil"} at https://bazil.org/bazil?go-get=1
bazil.org/bazil (download)
...
```

**Comment by peter-edge** [comment]
If you want to see an example of how I do this for go.pedge.io, do `curl -v https://go.pedge.io/protolog`

**Comment by jvinod** [comment]
@jupiturliu make update-test-deps seems to work for me...are you still hitting this problem?

**Comment by jupiturliu** [comment]
Fetching https://bazil.org/fuse?go-get=1
https fetch failed.
import "bazil.org/fuse": https fetch: Get http://bazil.org/fuse/?go-get=1: dial tcp 104.28.6.28:80: i/o timeout
package bazil.org/fuse: unrecognized import path "bazil.org/fuse"
Fetching https://bazil.org/fuse/fs?go-get=1
https fetch failed.
import "bazil.org/fuse/fs": https fetch: Get http://bazil.org/fuse/fs/?go-get=1: dial tcp 104.28.7.28:80: getsockopt: no route to host
package bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"
make: *** [update-test-deps] Error 1

**Comment by jupiturliu** [comment]
Still failed to fetch fuse

**Comment by jupiturliu** [comment]
It works now at my home computer , thanks
