### ISSUE TITLE
Support configurable port for StartServerApi

### ISSUE THREAD

**Issue by pault84** [libopenstorage/openstorage#62]
In order for the UI to hit OSD it needs a port to hit. currently we only provide a SOCK.

**Comment by peter-edge** [comment]
The Docker plugin API (which OSD has tried to replicate so far) has both a tcp option and unix socket option, OSD could just switch to the tcp option or provide both.

https://github.com/docker/docker/blob/master/docs/extend/plugin_api.md
https://github.com/peter-edge/go-dockerplugin/blob/master/dockerplugin.go

**Comment by pault84** [comment]
I'd suggest we'd provide both, make it either a flag or an opt during the start of OSD.

**Comment by jupiturliu** [comment]
@pault84 could you mind explaining a  little bit more the relationship between OSD and docker plugin API? I thought the OSD are plugin for the docker , isnot it?

Regards,
James

**Comment by jvinod** [comment]
@jupiturliu , yes OSD implements the docker plugin API. For each of the backend storage providers (nfs, ebs, pwx), it throws in a socket file over which docker communicates with OSD. The UI runs outside the OSD node, so it requires a TCP port to talk to OSD.  @pault84 wants the port exposed to the outside world.

**Comment by jupiturliu** [comment]
@jvinod thanks for explaination. I just checked the UI. so far, it can only create volume and list volumes. Are you planning to add other storage mangement features? Are you planning to use any other third party tools to monitor whole storage cluster?

**Comment by gourao** [comment]
I actually don't understand the question...   What do you mean by third
party tools to manage a cluster?

**Comment by jupiturliu** [comment]
@gourao Third party tools like Nagios to monitor the whole clustering status.

**Comment by jvinod** [comment]
@jupiturliu yes the UI is going to evolve in terms of storage management: storage cluster status, stats, alerts, events - at the volume as well as the container level. We don't plan to use any third party tools as of now - the  OSD REST API will evolve to provide all this information.

**Comment by jupiturliu** [comment]
@jvinod sounds very interesting. Supposely the OSD REST API is going to open source , right?  Are you guys working with any third parties for the RESTFUL API definition?

**Comment by gourao** [comment]
@jupiturliu The OSD REST API is already open source.  We are planning on working with 3rd party cluster management solutions and control planes (such as the Docker UCP).
