### ISSUE TITLE
sdk: Unable to set SchedulePolicy on volume

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#639]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
The SdkVolume.Update() call does not take the same objects used in SdkSchedulePolicy APIs. Instead it takes the yaml representation of this object as used by the older REST api.

**What you expected to happen**:

* SdkVolume.Update() API needs to have a method to set the schedule policy object name as created by SdkSchedulePolicy
* SdkVolume.Inspect() needs to return the [SchedulePolicy](https://libopenstorage.github.io/w/generated-api.html#sdkschedulepolicy) object as part of the VolumeSpec.

**Comment by ram-infrac** [comment]
We also need to take care of yaml parsing for Weekday sunday, since **time.Weekday treats sunday as 0** as a result yaml conversion returns no field in case of week day is sunday.

```
"snapshot_schedule" : "- freq: monthly\n  day: 5\n  hour: 10\n  minute: 10\n  retain: 3\n- freq: daily\n  hour: 10\n  minute: 10\n  retain: 1\n- freq: weekly\n  hour: 12\n  minute: 12\n  retain: 2\n",
```
*Note* : day field is missing for weekly freq
