### ISSUE TITLE
Switch out logrus as the logger

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#65]
it is very slow

**Comment by peter-edge** [comment]
Two self-promotions here:

- https://go.pedge.io/dlog is a package that puts an interface in front of logging packages. If you use dlog, you can use the stdlib logger, logrus, glog, and protolog.
- https://go.pedge.io/protolog is a logger based on using structured events, represented as protocol buffers. It's insanely fast, and encourages good logging practices. It's been in use for a long time, but documentation is lacking.

**Comment by peter-edge** [comment]
One other strategy I have done in the past: https://github.com/grpc/grpc-go/tree/master/grpclog

**Comment by jvinod** [comment]
I vote to stick with logrus - it does what we want it do - we use it's structured logging and is not in the i/o path. We can revisit this in the future if need be.

**Comment by peter-edge** [comment]
https://github.com/libopenstorage/openstorage/commit/86471b3fe52cc74d1494052df8caa10f55638fc6

**Comment by gourao** [comment]
@peter-edge No issues using dlog but can you submit a separate pull request for this (it's in refactor and refactor is very large to go through.)

**Comment by jvinod** [comment]
merged https://github.com/libopenstorage/openstorage/pull/111
