### ISSUE TITLE
Stop naming imports

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#66]
Examples:

```go
import (
  log "github.com.Sirupsen/logrus"
  graph "github.com/docker/docker/daemon/graphdriver"
)
```

It makes the code difficult to follow in terms of what packages are actually being used - only use if there is a conflict

**Comment by jvinod** [comment]
agreed...let's rename only in case of conflict.

**Comment by peter-edge** [comment]
https://github.com/libopenstorage/openstorage/commit/4541a8d6ae9568c21a2648d5a86801492f6da68a
