### ISSUE TITLE
Do not use VolumeDriver.String() as path

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#70]
https://github.com/libopenstorage/openstorage/blob/5c7001f9109a0ed4bc2422177a35ea17d00f618d/volume/drivers/test/driver.go#L40

Same file, what is line 39 for?

**Comment by peter-edge** [comment]
ping @jvinod

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
