### ISSUE TITLE
Write explicit copy functions for structs instead of dereferencing

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#72]
https://github.com/libopenstorage/openstorage/blob/5c7001f9109a0ed4bc2422177a35ea17d00f618d/volume/drivers/test/driver.go#L211

This has relatively undefined behavior within the context of this test package:
- if `volume.VolumeDriver` is a pointer, the pointer reference will be copied, ie modifications to the VolumeDriver will be made for both contexts
- if `volume.VolumeDriver` is a struct, the struct will be copied, i.e. modifications to the VolumeDriver will not be made for the original context
- same reasoning for `api.VolumeID`, which theoretically could be:

``` go
type VolumeID interface {
  fmt.Stringer
}

func NewVolumeID() VolumeID {
  return &volumeID{uuid.NewV4().String()}
}

type volumeID struct {
  value string
}

func (v *volumeID) String() string {
  return v.value
}

func (v *volumeID) SomeStatefulModificationThatWeAddedWhenSleepy() {
  if whyDidWeDoThis() {
    becauseWeWereSleepySadFace()
  }
}
```

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
