### ISSUE TITLE
Support for Object/BLOB Storage

### ISSUE THREAD

**Issue by WolfyLPDC** [libopenstorage/openstorage#722]
**Is this a BUG REPORT or FEATURE REQUEST?**:
It is a FEATURE REQUEST, but could be just a QUESTION.

**What happens**:
As defined in [the code](https://github.com/libopenstorage/openstorage/blob/7c7a44e95ad2583cc04ff5b06562d52e87fd09ee/cmd/osd/main.go), there are only two driver types available: block and file.

```
        // Register all volume drivers with the CLI.
	for _, v := range volumedrivers.AllDrivers {
		// TODO(pedge): was an and, but we have no drivers that have two types
		switch v.DriverType {
		case api.DriverType_DRIVER_TYPE_BLOCK:
			bCmds := osdcli.BlockVolumeCommands(v.Name)
			cmds := append(bCmds)
			c := cli.Command{
				Name:        v.Name,
				Usage:       fmt.Sprintf("Manage %s storage", v.Name),
				Subcommands: cmds,
			}
			app.Commands = append(app.Commands, c)
		case api.DriverType_DRIVER_TYPE_FILE:
			fCmds := osdcli.FileVolumeCommands(v.Name)
			cmds := append(fCmds)
			c := cli.Command{
				Name:        v.Name,
				Usage:       fmt.Sprintf("Manage %s volumes", v.Name),
				Subcommands: cmds,
			}
			app.Commands = append(app.Commands, c)
		}
          }
```

Is there any idea of adding the object/blob type? Has it been planned? There are some storage systems (including Portworx, CEPH or OpenStack Swift) that use that kind of storage and It would be interesting to have the option to work with them.

**Comment by lpabon** [comment]
I worked a lot in OpenStack Swift so I know it well. 

OpenStorage is a File/block attach and provisioner controller. Objects store containers/buckets are accessible over HTTP and there would be no need for attachment.

I would understand providing a "provisioner" for object store, but in a way OpenStorage has something like that for creating an ObjectStore on top of a provisioned volume: https://libopenstorage.github.io/w/master.generated-api.html#serviceopenstorageapiopenstorageobjectstore . This let's the driver implement the method of how it would be created on top of the volume. In Portworx we use Minio to create an object store on top of the volume. 

But for CEPH, or OpenStack Swift, or minio, sorry, but no, we do not have any plans to expand the API in that model

**Comment by WolfyLPDC** [comment]
@lpabon 
I understand your point and it makes sense, Object store is not the best option for attachment. Also, I am going to take a look to OpenStorageObjectstore implementation. As you can see, I'm just trying to know and understand the ins and outs of OpenStorage.

Thank you again.
