### ISSUE TITLE
Eliminate api.VolumeID?

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#76]
On typing primitives, my experience: leave dynamic values untyped, static values (ie enums) typed.

I used to type strings like api.VolumeID the same way, but my experience has been that it just gets in the way and doesn't add any protection. Engs still end up casting whenever something doesn't work, and generally its just a bunch of annoying casting.

For enums, using strings (as I mention in https://github.com/libopenstorage/openstorage/issues/71) leads to insonsistent usage, as some engs will just use the freeform value, even though another eng might look at the list of values and think this is all that is used. We already see this with Filesystem - btrfs is used as a Filesystem, but is not defined. There were more to on the branch proto: https://github.com/libopenstorage/openstorage/blob/proto/api/api.proto#L11

Thoughts?

**Comment by gourao** [comment]
This has been addressed in REFACTOR.

**Comment by jvinod** [comment]
merged https://github.com/libopenstorage/openstorage/pull/111
