### ISSUE TITLE
Need way to document parmeters for each driver type, and/or make them separate flags

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#77]
This is a big pain point for usage, and we get out of sync like this https://github.com/libopenstorage/openstorage/commit/53e38f5f00a35a393dd73c7b9d614fc2d40c46a5

There needs to be a way to know what parameters are available for each volume (and assumedly graph) driver. There's cute self-documenting ways to do this with protobuf if we ever get there in the future, but for now we really should enforce this in the code at the minimum. Right now we have constants in each place in the code.

**Comment by peter-edge** [comment]
docker-machine does this with separate flags fyi https://github.com/docker/machine/blob/6d5bc9938722499d2d24ca43fb296e1ae5c637e8/drivers/amazonec2/amazonec2.go#L72

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
