### ISSUE TITLE
Choose between /var/lib/osd and /var/lib/openstorage

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#78]
```
config/config.go:26:    DriverAPIBase      = "/var/lib/osd/driver/"
config/config.go:27:    GraphDriverAPIBase = "/var/lib/osd/graphdriver/"
config/config.go:30:    MountBase          = "/var/lib/osd/mounts/"
graph/drivers/fuse/graph.go:29: virtPath = "/var/lib/openstorage/fuse/virtual"
graph/drivers/fuse/graph.go:30: physPath = "/var/lib/openstorage/fuse/physical"
volume/drivers/buse/buse.go:27: BuseMountPath = "/var/lib/openstorage/buse/"
volume/drivers/vfs/vfs.go:21:   volumeBase = "/var/lib/osd/"
volume/drivers/nfs/nfs.go:29:   nfsMountPath = "/var/lib/openstorage/nfs/"
```

This should really be a higher-up constant, probably in a common package.

**Comment by jvinod** [comment]
yes agreed, right now it's in config.go and all drivers should use that.

**Comment by peter-edge** [comment]
What do you mean? There needs to be a standard layout here that is enforced as much as possible through the code. For example, I'm not sure what to do with fuse/, buse/, nfs/, etc...mounts also don't really need to go here and could really go in a tmp directory.

**Comment by jvinod** [comment]
Everything goes to go under directories defined in config.go

All the driver stuff should go under:
/var/lib/osd/<driver_name>

**Comment by gourao** [comment]
@peter-edge @jvinod Any transient directory or sock file created should go under /var/run/osd.

I agree that this should be enforced in the code.

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
