### ISSUE TITLE
Switch from github.com/codegangsta/cli to github.com/spf13/cobra

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#80]
Cobra is becoming the new standard, and IMO is much higher quality. It's also what Kubernetes uses, and matches will with github.com/spf13/viper.

Also generally split openstorage commands away from implementation (ie openstorage should be a pure library first, commands on top) - this might be better as a separate issue.

**Comment by gourao** [comment]
@peter-edge Sure - though I think it's slightly less in terms of a priority compared to other tasks.  Your call.

**Comment by peter-edge** [comment]
Ya this isn't high priority, but will keep the issue around for now

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
