### ISSUE TITLE
Switch from docker hub to quay.io

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#81]
Or gcr.io (I personally like quay.io more though). In my experience, both are more reliable and much faster.

**Comment by jvinod** [comment]
Is this to push the openstorage/ost container? we do need to push it to docker hub.. but we could do quai/gcr as well

**Comment by peter-edge** [comment]
Why do you need to push to docker hub?

**Comment by jupiturliu** [comment]
@peter-edge I guess the purpose is to let any users  launch osd from docker hub

**Comment by gourao** [comment]
@peter-edge Can we defer this topic till we get things more stable?  This is not causing anyone too much trouble at the moment.

**Comment by peter-edge** [comment]
Actually this is one of the few ones I think matters to get in sooner than later - once a repository is more popular, it's harder to get the user base to switch from docker hub to quay. It takes about 5 minutes to set this up, I can walk someone through it (you need to make an openstorage account).

**Comment by peter-edge** [comment]
@gourao @jvinod if I can convince you two this a good idea, can you set up a portworx or openstorage organization on quay.io, make me an administrator, and I'll set this up soon? heh :)

**Comment by peter-edge** [comment]
Another reason, rkt compatibility automatically Get Started with rkt Containers in Three Minutes
https://coreos.com/blog/getting-started-with-rkt-1.0.html

**Comment by peter-edge** [comment]
The last build pushed to https://hub.docker.com/r/openstorage/osd was three months ago, so since this has not been updated, let's move over to quay.io

@gourao or @jvinod, what I need from you:

- Make an openstorage organization on quay.io
- Add all of us to it as admins

Then, I will:

- Push the initial image to quay.io
- Set it up properly
- Add a Makefile command docker-push to push to quay.io

Then, we will:

- Setup Jenkins to do this on each successful build.

**Comment by gourao** [comment]
@ankitgd 

Jenkins is down at the moment due to changes needed for the right docker version.

@peter-edge we have so much going on, can we defer this and close this issue for now?

**Comment by jvinod** [comment]
Jenkins was upgraded to 1.10

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
