### ISSUE TITLE
No config file in daemon mode allowed?

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#83]
I was expecting this to work:

```
$ sudo $(which osd) -d --driver name=vfs
WARN[0000] OSD configuration file not specified.  Visit openstorage.org for an example.
```

Should it not? I can see arguments both ways, but was wondering what the `--driver` flag is for otherwise :)

**Comment by jvinod** [comment]
Good catch, it must be a leftover - the daemon mode does expect a config file. We should blow that arg away..

**Comment by peter-edge** [comment]
Does this mean you want to remove the --driver flag?

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
