### ISSUE TITLE
Specific flags for each driver type

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#84]
```
$ sudo $(which osd) vfs create --help
NAME:
   osd vfs create - create a new volume

USAGE:
   osd vfs create [command options] [arguments...]

OPTIONS:
   --label, -l          Comma separated name=value pairs, e.g name=sqlvolume,type=production
   --size, -s "1000"        specify size in MB
   --fs "ext4"          filesystem to be laid out: none|xfs|ext4
   --seed           optional data that the volume should be seeded with
   --block_size, -b "32"    block size in Kbytes
   --repl, -r "1"       replication factor [1..2]
   --cos "1"            Class of Service [1..9]
   --snap_interval, --si "0"    snapshot interval in minutes, 0 disables snaps
```

This is the same across all driver types. I am pretty sure `--cos` as an example is just for AWS.

**Comment by jvinod** [comment]
Yep, we can do that just the way we have specific commands available per driver type.

**Comment by gourao** [comment]
The options are common across driver types and a driver that does not need an option can simply ignore it (or generate an error if it wants).  Closing this issue.

**Comment by peter-edge** [comment]
This isn't a sufficient explanation to me - an end user should not have to know whether a flag is ignored or not for a specific driver, that is not something I think is OK. Keeping this as a tracking issue

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
