### ISSUE TITLE
Driver create documentation should match expected values

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#85]
```
$ sudo $(which osd) vfs create
create: missing parameter "name" - Invalid number of arguments
```

Name was not mentioned anywhere :) I basically assumed it needed a name, but was wondering if osd might generate a name for me.

**Comment by peter-edge** [comment]
Hmm, maybe it does?

```
$ sudo $(which osd) vfs create foo
93fd9f5a-fb13-4cf4-9224-013ec82eb51d
$ sudo $(which osd) vfs inspect foo
[]
$ echo $?
0
$ sudo $(which osd) vfs inspect 93fd9f5a-fb13-4cf4-9224-013ec82eb51d
[
 {
  "ID": "93fd9f5a-fb13-4cf4-9224-013ec82eb51d",
  "Source": null,
  "Readonly": false,
  "Locator": {
   "Name": "foo",
   "VolumeLabels": null
  },
  "Ctime": "2015-12-14T18:00:53.223663618Z",
  "Spec": {
   "Ephemeral": false,
   "Size": 1048576000,
   "Format": "ext4",
   "BlockSize": 32768,
   "HALevel": 1,
   "Cos": 1,
   "Dedupe": false,
   "SnapshotInterval": 0,
   "ConfigLabels": null
  },
  "Usage": 0,
  "LastScan": "2015-12-14T18:00:53.223665242Z",
  "Format": "vfs",
  "Status": "Up",
  "State": 2,
  "AttachedOn": "",
  "DevicePath": "/var/lib/osd/93fd9f5a-fb13-4cf4-9224-013ec82eb51d",
  "AttachPath": "",
  "ReplicaSet": null,
  "Error": ""
 }
]
```

So issues here:

- No documentation about the id that is returned
- When I inspect based on the name (that I was asked to give), nothing is returned, and error code is 0
- Can only inspect based on returned id

**Comment by jvinod** [comment]
Yep, we need to fix docs. Enumerate allows you to list volumes by specific criteria including name - are you suggesting that inspect do the same?

**Comment by peter-edge** [comment]
See the bullet points - what would you like to do?

**Comment by jvinod** [comment]
we need to fix the first two bullets:
- No documentation about the id that is returned
- When I inspect based on the name (that I was asked to give), nothing is returned, and error code is 0

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
