### ISSUE TITLE
Handle SIGINT, SIGTERM

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#86]
We should handle shutdown signals in the binary - when osd is killed, we should have a graceful shutdown that includes things like unmounting. We also should consider what this does in terms of docker's view of osd volumes.

**Comment by jvinod** [comment]
SGTM - we can't unmount or detach volumes that are in use.  

Also we always need to be able to recover from an ungraceful shutdown. Drivers are expected to recover and volumes mounted in docker are expected to service I/O seamlessly.

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
