### ISSUE TITLE
strings.Contains(err.Error(), "...")

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#89]
https://github.com/libopenstorage/openstorage/blob/803a2df99fa2ddc2304de2a7dfc72e1982791f3e/cluster/database.go#L22

If you're going to have typed errors, freeform strings will lead to bugs. I prefer a bool for key not found, but if we have this, it has to be something other than string compares.

**Comment by jvinod** [comment]
+ 1 yes, agreed. Don't like it - maybe the new etcd library has typed errors that we can use instead

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
