### ISSUE TITLE
Simple volume driver with zero configuration for development.

### ISSUE THREAD

**Issue by kunalkushwaha** [libopenstorage/openstorage#9]
I think a simple volume which resides on local host can be useful for new / first time user of osd.

A btrfs or nfs needs some configuration, but a file/folder based volume will be helpful while trying the osd, which require zero configuration.

**Comment by jvinod** [comment]
@kunalkushwaha Sounds good. Let's do a local driver with zero config. Thanks

**Comment by peter-edge** [comment]
Can this be closed? @kunalkushwaha

**Comment by kunalkushwaha** [comment]
Code is merged, Closing.
