### ISSUE TITLE
Make sure vendors are added

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#90]
docker run \
		--privileged \
		-v /var/run/docker.sock:/var/run/docker.sock \
		-e AWS_ACCESS_KEY_ID \
		-e AWS_SECRET_ACCESS_KEY \
		-e TAGS \
		-e PKGS \
		-e BUILDFLAGS \
		openstorage/osd-dev \
			make test
go test -tags "daemon btrfs_noversion have_btrfs have_unionfs" github.com/libopenstorage/openstorage/api github.com/libopenstorage/openstorage/api/client github.com/libopenstorage/openstorage/api/server github.com/libopenstorage/openstorage/cli github.com/libopenstorage/openstorage/cluster github.com/libopenstorage/openstorage/cmd/osd github.com/libopenstorage/openstorage/config github.com/libopenstorage/openstorage/graph github.com/libopenstorage/openstorage/graph/drivers github.com/libopenstorage/openstorage/graph/drivers/layer0 github.com/libopenstorage/openstorage/graph/drivers/proxy github.com/libopenstorage/openstorage/pkg/chaos github.com/libopenstorage/openstorage/pkg/device github.com/libopenstorage/openstorage/pkg/mount github.com/libopenstorage/openstorage/pkg/seed github.com/libopenstorage/openstorage/pkg/stats github.com/libopenstorage/openstorage/volume github.com/libopenstorage/openstorage/volume/drivers github.com/libopenstorage/openstorage/volume/drivers/aws github.com/libopenstorage/openstorage/volume/drivers/btrfs github.com/libopenstorage/openstorage/volume/drivers/buse github.com/libopenstorage/openstorage/volume/drivers/fuse github.com/libopenstorage/openstorage/volume/drivers/nfs github.com/libopenstorage/openstorage/volume/drivers/pwx github.com/libopenstorage/openstorage/volume/drivers/test github.com/libopenstorage/openstorage/volume/drivers/vfs
graph/drivers/unionfs/unionfs.go:27:2: cannot find package "github.com/docker/docker/pkg/directory" in any of:
	/go/src/github.com/libopenstorage/openstorage/vendor/github.com/docker/docker/pkg/directory (vendor tree)
	/usr/local/go/src/github.com/docker/docker/pkg/directory (from $GOROOT)
	/go/src/github.com/docker/docker/pkg/directory (from $GOPATH)

**Comment by peter-edge** [comment]
http://emma.openstorage.org/job/Openstorage/379/console

**Comment by jvinod** [comment]
@peter-edge our vendor is a bit behind. A lot breaks when we do a make deps, make vendor - could I assign this to you to get that up to date? Feel free to assign back.
