### ISSUE TITLE
OIDC token may have rules and groups under a namespace

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#909]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE

**What happened**:
OIDC Issuers like Auth0.com place custom claims under a namespace. According to the [spec](https://openid.net/specs/openid-connect-core-1_0.html#AdditionalClaims), this is a recommendation and it should be supported by the OpenStorage.

**What you expected to happen**:
Admin should provide a namespace during server configuration for the `roles`, `groups`, and any other claims that are custom to OpenStorage.

**How to reproduce it (as minimally and precisely as possible)**:
See [Auth0.com: Add custom claims to token](https://auth0.com/docs/scopes/current/sample-use-cases#add-custom-claims-to-a-token)

**Example**

```
  "https://openstorage.io/roles": [
    "system.admin"
  ],
  "https://openstorage.io/groups": [
    "engineering",
    "portworx"
  ],
```

**Comment by wallnerryan** [comment]
@lpabon should we investigate other OIDC providers to see if this is standard? Thought process is maybe there is a way to support Auth0 and others.

**Comment by lpabon** [comment]
>@lpabon should we investigate other OIDC providers to see if this is standard? Thought process is maybe there is a way to support Auth0 and others.

Definitely.
