### ISSUE TITLE
func init() is used too much, eliminate most globals so openstorage can be a library

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#92]
```
$ agg 'func init'
pkg/chaos/chaos.go:123:func init() {
config/config.go:53:func init() {
graph/drivers/proxy/proxy.go:14:func init() {
graph/graphdriver.go:58:func init() {
graph/drivers/layer0/layer0.go:62:func init() {
graph/drivers/unionfs/unionfs.go:234:func init() {
volume/drivers/vfs/vfs.go:183:func init() {
volume/volume.go:180:func init() {
volume/drivers/buse/buse.go:361:func init() {
volume/enumerator_test.go:133:func init() {
volume/drivers/pwx/pwx.go:48:func init() {
volume/drivers/btrfs/btrfs.go:218:func init() {
volume/drivers/test/driver.go:343:func init() {
volume/drivers/aws/aws.go:603:func init() {
volume/drivers/nfs/nfs.go:380:func init() {
api/client/client.go:145:func init() {
api/client/request_test.go:44:func init() {
```

Going through this, it seems like init is used in a lot of cases for global variable that should not be global variables, or for initialization that has external side-effects (os.MkdirAll(...), for example). We should strive for openstorage to be a library first, with a command line tool and daemon built on top of it.

**Comment by jvinod** [comment]
Most inits are related to 'registration' as a driver. If they're not, let's address them on a case by case basis.

**Comment by gourao** [comment]
I don't see the problem since all of the modules seem to be following a pattern...

**Comment by peter-edge** [comment]
The `Register` functions are not great either, they should be eliminated - the usage of global state here is really not good, I have to be frank here, I'm sorry

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
