### ISSUE TITLE
Audit for existing casting/nil/panic vulnerabilities

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#96]
Example: https://github.com/libopenstorage/openstorage/blob/8d07329468ef709838e443dc17b1eecf2c7cf77d/cluster/manager.go#L149
- How are we sure that e.Value is not nil?
- How are we sure that e.Value can be case to ClusterManager?

Both of these should be checked, ie e.Value == nil -> error, clusterManager, ok := e.Value.(ClusterManager)

**Comment by jvinod** [comment]
agreed, let's find these occurrences and fix them.

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
