### ISSUE TITLE
Comments on packages and public types should be GoDoc friendly

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#97]
Package comments always start with "Package name_of_package ...", types are always commented wit the name of the type:

``` go
// Foo is a ...
type Foo struct {
}

// Bar does ...
type Bar interface {
}

var (
  // Name is the volume driver name.
  //
  // TODO(osd team): more descriptive names for these variables  
  Name = "btrfs"
)
```

This will fail golint otherwise.

**Comment by jvinod** [comment]
+1 and will enforce going forward.

**Comment by lpabon** [comment]
Closing since it has had no update for more than 6 months. Please reopen if needed.
